### ISSUE TITLE
AWS Lambda & API Gateway Example

### ISSUE THREAD

**Issue by c-bata** [line/line-bot-sdk-python#10]
Hi! I created a  LINE Bot on AWS Lambda + API Gateway using [Chalice](https://github.com/awslabs/chalice).

https://github.com/c-bata/chalice-linebot

How would you like to add it on README as one example?
If you are ok, I'll send a Pull Request :)

**Comment by be-hase** [comment]
It's interesting example app ! 👍 
I'm also interested in the serverless architecture.

How would you like to add this on wiki ?
https://github.com/line/line-bot-sdk-python/wiki/Projects-Using-SDK

**Comment by c-bata** [comment]
I'm so glad about your suggestion!
Please go ahead and proceed with it. 👍

**Comment by be-hase** [comment]
Thanks 😃
I have added on our wiki.
