### ISSUE TITLE
DatetimePickerTemplateAction mode="datetime" failed

### ISSUE THREAD

**Issue by xiaosean** [line/line-bot-sdk-python#100]
I use the DatetimePickerTemplateAction part of unittest 

https://github.com/line/line-bot-sdk-python/blob/master/tests/api/test_send_template_message.py 

but below part is failed, time  or date mode work fine.

~~~python
DatetimePickerTemplateAction(
                                label="datetime picker datetime",
                                data="action=sell&itemid=2&mode=datetime",
                                mode="datetime",
                                initial="2013-04-01T10:00",
                                min="2011-06-23T00:00",
                                max="2017-09-08T23:59"
                            )

~~~

**Comment by be-hase** [comment]
Maybe, your `label` property is large.

![2018-06-20 15 41 14](https://user-images.githubusercontent.com/903482/41641506-664ede2c-74a0-11e8-92e9-d00c1c6a8dc7.png)

Depending on how it is used, it must be at most 20 length.
