### ISSUE TITLE
[Feature Request] Asynchronous/Asyncio support

### ISSUE THREAD

**Issue by Shivelight** [line/line-bot-sdk-python#101]
It would be nice if asynchronous processing natively supported. I think this feature is necessary and reasonably easy to implement without breaking any code or compatibility as we only need to write new API and HTTP client that support async.

If you agree with this or maybe you have a better idea, I would be happy to work on it.

EDIT: I thought I was writing a commit message, here are some sparkles :sparkles: :sparkles: :sparkles:

**Comment by cwkfr** [comment]
I've made my own, closing this as no high interest in it.

**Comment by alfredfrancis** [comment]
@Shivelight  can you merge your solution with this

**Comment by Shivelight** [comment]
@alfredfrancis I don't think my solution is good to merge with this; it is a duplicate code infused with async-await. I'm not a pro, but in my opinion, a better solution might be architecture change that allows you to use sync and async HTTP client interchangeably. Personally, I like [osuapi](https://github.com/khazhyk/osuapi/blob/master/osuapi/connectors.py) connectors solution. Whatever the solution is, it's the maintainer decision.

**Comment by tokuhirom** [comment]
If we're dropping Python 3.6- support in the next major release, we can support async natively.
[python.org document](https://www.python.org/downloads/) says, python 3.5 will become EOL at 2020-09-13. It's very soon :)

Is it time to support async?

**Comment by Shivelight** [comment]
> Is it time to support async?

A yes from me, that would be awesome :tada:

**Comment by alfredfrancis** [comment]
> Is it time to support async?
yes

**Comment by uezo** [comment]
I've just released aiolinebot, async api client library - strictly saying, not client library but async client generator from line-bot-sdk.

https://github.com/uezo/aiolinebot

This is a kind of hack, but by this way it's easy to keep up-to-date with the API updates until async is officially supported.(very soon?)

I hope this will be help for you and our community😃

**Comment by CircleOnCircles** [comment]
> I've just released aiolinebot, async api client library - strictly saying, not client library but async client generator from line-bot-sdk.
> 
> [uezo/aiolinebot](https://github.com/uezo/aiolinebot)
> 
> This is a kind of hack, but by this way it's easy to keep up-to-date with the API updates until async is officially supported.(very soon?)
> 
> I hope this will be help for you and our community😃

quoting #310 

for those who want a quick solution of this pls use 

https://github.com/codustry/line-bot-sdk-python/tree/async-support-for-handler 

by pip or `poetry add git+https://github.com/codustry/line-bot-sdk-python#async-support-for-handler`

```python

handler = WebhookHandlerV2(settings.LINE_SECRET)

@router.post("/line")
async def handle_line_webhook(
        request: Request, 
		signature: str = Header(None, alias="X-Line-Signature")
):
    # get request body as text
    body = await request.body()
    body = body.decode()

    # handle webhook body
    try:
        await handler.handle_async(body, signature)
    except InvalidSignatureError as e:
        print(
                "Invalid signature. Please check your channel access token/channel secret."
        )
        raise e

@handler.add(MessageEvent, message=TextMessage)
async def handle_message(event: MessageEvent):
    response_to_magic_word(event)
```

This comes from a fastapi framework.

And a plus that uezo/aiolinebot is fully compatible with https://github.com/codustry/line-bot-sdk-python/tree/async-support-for-handler 🥰

**Comment by tokuhirom** [comment]
I created new PR #340  to support this feature. If you have any comments on the PR(especially interface), feel free to submit a comment to the PR.
