### ISSUE TITLE
Cant use BubbleStyle in FlexMessage template

### ISSUE THREAD

**Issue by ferdi554** [line/line-bot-sdk-python#111]
Hello, i cant use BubbleStyle in my FlexMessage template, here is my code:

`styles=BubbleStyle(
                        footer=BlockStyle(
                            background_color='#000000'
                        )
                    )`

that code cause an error <LineBotApiError [A message (messages[0])┬áin the request body is invalid]>. Is this a bug or my bad ? :D

**Comment by tokuhirom** [comment]
You can get error details from LineBotApiError instance.

Please look a code at here: https://github.com/line/line-bot-sdk-python/blob/ccb97deb9445a1ea09058584727e09f6870a4732/examples/flask-kitchensink/app.py#L84-L90

```
    try:
        handler.handle(body, signature)
    except LineBotApiError as e:
        print("Got exception from LINE Messaging API: %s\n" % e.message)
        for m in e.error.details:
            print("  %s: %s" % (m.property, m.message))
        print("\n")
```

**Comment by ferdi554** [comment]
The error details is `[{"message": "unknown field", "property": "/styles/type"}]`

Is there any example for using BubbleStyle in FlexMessage template ?

**Comment by ferdi554** [comment]
![image](https://user-images.githubusercontent.com/10397947/42120915-e663a836-7c4d-11e8-86b2-e9c2487ec155.png)

why there is a 'type' key at 'styles' key ?

I have resolved this issue by removing that 'type' key 💃 

Thank you

**Comment by nottyo** [comment]
I got this problem as well. The BubbleContainer define default `styles.type` as `carousel` but actually there is no `type` field in bubble `styles` How can I fix it?

![image](https://user-images.githubusercontent.com/8110002/42124692-ec39a8ac-7c91-11e8-8a71-9c68e0579cf0.png)
