### ISSUE TITLE
Add test codes for json serialize of model

### ISSUE THREAD

**Issue by be-hase** [line/line-bot-sdk-python#114]
To prevent like a this issues.
https://github.com/line/line-bot-sdk-python/issues/111

**Comment by tkgauri** [comment]
Need to add test cases for models present in `line-bot-sdk-python/linebot/models/`
Nice to have!

**Comment by okue** [comment]
**test_messages**.py is added in directory **tests/models/** (#177)

**Comment by okue** [comment]
Json-serializing-test should be added for the following modules:
- [ ] actions.py
- [ ] flex_message.py
- [ ] imagemap.py
- [ ] send_messages.py
- [ ] template.py
