### ISSUE TITLE
can i via user_id find user set id(LINE ID) or phone number

### ISSUE THREAD

**Issue by lemonnen** [line/line-bot-sdk-python#123]
can i via user_id find user set ID(LINE ID) or user set phone number?
via 'Uxxxxxx(32)' to find follow picture's ID(LINE ID) or other way can find LINE ID?
https://imgur.com/1Hqkztw.png

**Comment by clsung** [comment]
No you can't.

- Different user IDs are generated based on the provider of the channel. As long as channels have the same provider, regardless of whether the channel is for LINE Login or Messaging API, the same user ID is used for the users of the channels.

Ref: https://developers.line.me/en/faq/
