### ISSUE TITLE
invalid uri scheme

### ISSUE THREAD

**Issue by petrusandhyprabowo** [line/line-bot-sdk-python#124]
I don't understand why this is always error "invalid uri scheme", what's wrong with this json uri scheme ?
![image](https://user-images.githubusercontent.com/12115442/45873800-7b4e5580-bdbd-11e8-860f-0b17b84ac10f.png)

Thank you

**Comment by tokuhirom** [comment]
The error message says the content body in your request is invalid.
The wrong field is specified in the `property` property. `body['template']['columns'][0]['thumbnailImageUrl']` may be invalid. Please check the field.

**Comment by petrusandhyprabowo** [comment]
I change url of image, I think is not all url image can use in this property.
Thanks for your advice @tokuhirom

**Comment by eggeggss** [comment]
you can try to change the url to  https, it's fine in iPhone, but have the same error in Android
