### ISSUE TITLE
how to return image back to the user

### ISSUE THREAD

**Issue by pandailing** [line/line-bot-sdk-python#135]
simple question here:

how can i return any image sent by user back to them?

some kind things like this but with images: 

> @handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text=event.message.text))

**Comment by tokuhirom** [comment]
Sorry about my late reply. You can send an image message like the following code.

```
        line_bot_api.reply_message(
            event.reply_token,
            ImageSendMessage(url, url)
        )
```
