### ISSUE TITLE
Member Join Event

### ISSUE THREAD

**Issue by qoo23502004** [line/line-bot-sdk-python#136]
https://github.com/line/line-bot-sdk-python/blob/e7383382336c328d24591a99d7535c3250f0452c/linebot/webhook.py#L26

A new event name "Member Join Event" in Official Document 
How to use it?

**Comment by be-hase** [comment]
Sorry, It is not yet implemented in python SDK.
We'll do it.

**Comment by qoo23502004** [comment]
> Sorry, It is not yet implemented in python SDK.
> We'll do it.

It's OK.
I finish it.
My chatbot can auto say "welcome" for the new user when they joined!
But it's just a simple version.

**Comment by tokuhirom** [comment]
This issue was duplicate with #142. And implemented in #148

**Comment by bottsjw** [comment]
Looking forward to this being in a future release. Any eta?

**Comment by brokennaxier** [comment]
> > Sorry, It is not yet implemented in python SDK.
> > We'll do it.
> 
> It's OK.
> I finish it.
> My chatbot can auto say "welcome" for the new user when they joined!
> But it's just a simple version.

Mine is not working like that. Can you tell me how it worked?

**Comment by qoo23502004** [comment]
> > > Sorry, It is not yet implemented in python SDK.
> > > We'll do it.
> > 
> > 
> > It's OK.
> > I finish it.
> > My chatbot can auto say "welcome" for the new user when they joined!
> > But it's just a simple version.
> 
> Mine is not working like that. Can you tell me how it worked?

I finish the member join event by myself.
you can try to edit the webhook.py and your app.py

In app.py : 
@handler.add(MemberJoinEvent)
def handle_memberJoined(event):
