### ISSUE TITLE
issue with get userId

### ISSUE THREAD

**Issue by jiahong-chen** [line/line-bot-sdk-python#139]
when i want to use follow event to get userId, i found 'SourceUser' object has no attribute 'userId'. So, i viewed the source.py source code and found i need use event.source.user_id instead of event.source.userId.

**Comment by be-hase** [comment]
In the Developer center's JSON base document, it is described as `userId` (camel case), but in Python SDK `user_id` (snake case) is correct.

In Python, snake case is recommended by [pep8](https://www.python.org/dev/peps/pep-0008/).

e.g.
- `replyToken` -> `reply_token`
- `altText` -> `alt_text`
