### ISSUE TITLE
bot official cannot use replace text

### ISSUE THREAD

**Issue by wongmu** [line/line-bot-sdk-python#140]
## Do this before creating an issue

- Check our [developer documentation](https://developers.line.me/en/docs/) and [FAQ](https://developers.line.me/en/faq/messaging-api/) page for more information on LINE bots and the Messaging API
- Make sure your issue is **related to** the LINE Bot SDK. For general questions or issues about LINE bots, create an issue on the [LINE Platform feedback](https://github.com/line/line-platform-feedback) repository. Note that we don't provide technical support.

## When creating an issue

- Provide detailed information about the issue you had with the SDK
- Provide logs if possible
```
elif text == '/lokasi ':
        sep = text.split(" ")
        search = text.replace(sep[0] + " ","")
        try:
            r = requests.get("https://example.com/{}".format(urllib.parse.quote(search)))
            data=r.text
            data=json.loads(data)
            message = LocationSendMessage(
                title=str(data["data"]["country"]),
                address=str(data["data"]["address"]),
                latitude=str(data["data"]["latitude"]),
                longitude=str(data["data"]["longitude"])
            )
            line_bot_api.reply_message(event.reply_token, message)
```

how to bot can use command /lokasi name city>

**Comment by tokuhirom** [comment]
i can't understand what do you want
