### ISSUE TITLE
Timeout when send message

### ISSUE THREAD

**Issue by AwesomePeople** [line/line-bot-sdk-python#146]
Hi everyone, before I send message to user. I try to scrape data on website, It cause timeout ( I had set timout=100, but I did't help solve problem).
Error message: 
`linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, error_response={"details": [], "message": "Invalid reply token"}`

**Comment by tokuhirom** [comment]
Reply API is only available for the interactive operation. If you need interval while sending reply, you need to call the push API instead.

**Comment by AwesomePeople** [comment]
@tokuhirom Thanks for so quickly response. I will try the push API. Thank you so much <3

**Comment by AwesomePeople** [comment]
@tokuhirom , It worked perfectly <3 Thank you <3
