### ISSUE TITLE
How can I set altUri.desktop property for URIAction?

### ISSUE THREAD

**Issue by clhsieh** [line/line-bot-sdk-python#154]
There is a altUri.desktop property in [api reference](https://developers.line.biz/en/reference/messaging-api/#uri-action)
But I can't see it in actions.py
Cant I use it using any other method?
https://github.com/line/line-bot-sdk-python/blob/1b38bfc2497ff3e3c75be4b50e0f1b7425a07ce0/linebot/models/actions.py#L120-L141

**Comment by tkgauri** [comment]
Hello @clhsieh,
Thank you for reporting.

Currently, this property is not available in bot-sdk-python. Sorry for the inconvenience.
We are planning to add support for this property https://github.com/line/line-bot-sdk-python/issues/155 

Thanks!

**Comment by tkgauri** [comment]
Released 1.10.0:  https://github.com/line/line-bot-sdk-python/releases
