### ISSUE TITLE
What's the different between push and reply message?

### ISSUE THREAD

**Issue by hrchu** [line/line-bot-sdk-python#157]
When I got a message from a user, I can response it via either push or reply API, but what's the difference? Let me guess, Pushed messages are counted into charged, and replied messages are free? I don't find any documents mentioned it.

**Comment by tkgauri** [comment]
REPLY_MESSAGE lets you send "reply messages" in response to events such as a user's message.

PUSH_MESSAGE lets you send "push messages" directly to users at any time.

**Comment by hrchu** [comment]
Yeap I know that, but what I curious about is the difference between them in the response scenario. No any difference in the scenario?

**Comment by tkgauri** [comment]
Hello,

Please refer to official documentation:
https://developers.line.biz/en/reference/messaging-api/#send-reply-message

Also, please use our community Q&A website for questions like this.
https://www.line-community.me/questions

As we do not provide technical support here, if you need technical support please check:
https://developers.line.biz/en/faq/#how-can-i-get-technical-support-2017-07-24

Thanks!
