### ISSUE TITLE
How to get the url of my channel icon?

### ISSUE THREAD

**Issue by phlinhng** [line/line-bot-sdk-python#166]
I am developing a web platform for controlling my line chatbot. I want to make the icon of my chatbot display on my page so I need the url of my channel icon. While I can only find the tutorial of how to get user's profiles instead of my profile. Is it possible to get my channel icon url by api?

**Comment by tkgauri** [comment]
Hello,
It is not possible to get channel icon url at this point of time.
Sorry for the inconvenience!

Thanks!
