### ISSUE TITLE
Follow event on Join invite?

### ISSUE THREAD

**Issue by ivan98** [line/line-bot-sdk-python#17]
I am using v1.0.2 with the kitchenSink example.
My JoinEvent handler is

```
@handler.add(JoinEvent)
def handle_join(event):
    wplog.logger.info("Got join event")
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text='Joined this ' + event.source.type))
```

In a group chat between user ABC and bot, sequence of events:
1. User ABC send invite to user DEF
2. Bot sees Join Event and says "Joined this group"
3. 5 mins later, user DEF accepts invite and joins group
4. User DEF did **not** see Bot's msg "Joined this group"

In this correct? Why?

My expectation is:
1. User ABC send invite to user DEF
2. 5 mins later, user DEF accepts invite and joins group
3. Bot sees Join Event and says "Joined this group" (a welcome msg)
4. User DEF sees Bot's msg "Joined this group" (a welcome msg)

Thank you.

**Comment by be-hase** [comment]
Hi, @ivan98 
It is reproduced on my environment.
We are now investigating this issue.
Thanks for your report.

**Comment by be-hase** [comment]
Hi, @ivan98 .

We will fix this issue in a few days.
We apologize for the inconvenience.
Thanks.

**Comment by be-hase** [comment]
We fixed this issue.
Now, join/leave event is occurred when the Bot  joins/leaves group.
