### ISSUE TITLE
event.source.user_id causes error with new memberJoinEvent

### ISSUE THREAD

**Issue by bottsjw** [line/line-bot-sdk-python#172]
using the new memberJoinEvent handle in 1.10
I'm able to capture the 
event.source.group_id 

but the event.source.user_id results in an error.

log.logger.info('Event Source:'+event.source.group_id)
<result is group ID>

log.logger.info('User Source Name:'+event.source.user_id)
<result TypeError: cannot concatenate 'str' and 'NoneType' objects>

Based on the documentation, it seems with this event there are multiple event objects with 'joined.members' responsible for the user_ID

I have also tried
event.joined.member.user_id
event.joined.members.user_id

**Comment by tkgauri** [comment]
event.joined.members should work. 
Check the sample Member join event given on the right hand side here: 
https://developers.line.biz/en/reference/messaging-api/#source-user

**Comment by bottsjw** [comment]
I was able to get this to work.
Because joined.members is an array, I needed to select the first object. I guess the API is designed to support a crowd joining all at once. Can’t figure that use case but, oh well. 🤷‍♂️

This format does return the UserID.

`event.joined.members[0].user_id`
same for leavers...
`event.left.members[0].user.id`

Closing this issue. Thanks!
