### ISSUE TITLE
What is the <to> in push_message command in Messaging API?

### ISSUE THREAD

**Issue by you4jang** [line/line-bot-sdk-python#19]
Hi, I'm new to Line Messanger and Messaging API of line-bot-SDK-python.

I have tried to use the push_message command in Messaging API in order to send messages to my friends, but I can't send messages. How to get the <to>, ID of the receiver, of my friends, groups, rooms?  Where can I see those informations? What is ID of the receiver?

Thanks.

**Comment by tokuhirom** [comment]
You can get IDs for to from payload of the webhook.

**Comment by you4jang** [comment]
Thank you. I need to find out what webhook is.

**Comment by you4jang** [comment]
Can I ask something? What is the webhook? Where can I find out? Was it provided by you Line platform? Or is it what I make?

Thank you

**Comment by be-hase** [comment]
Have you read this page?
https://devdocs.line.me/en/

Thanks.

**Comment by you4jang** [comment]
Hi, be-hase.

Thank you for your reply. I have read that page and had a rough idea of what webhook is. But I can't understand how to create it, where to be it no more. Webhook is a user-defined HTTP POST callback, so webhook is a web server which is doing web service created by me, developer. Am I right?

Thank you.

**Comment by jar555** [comment]
Webhook is not webserver. It can be used to deal with a POST method.

If you want to create your own POST call, there are some apps and websites that can allow you to make your own post request. Here is a good app that I use: https://www.getpostman.com/apps

**Comment by be-hase** [comment]
@you4jang 
Webhook is a mechanism for realizing information provision from one application to another one.

If you send a message to the BOT, the LINE platform creates the message's information in JSON format and sends it to your server.

Simplified diagram.
![](https://cloud.githubusercontent.com/assets/903482/20452349/f9efd9ec-ae4a-11e6-88a4-06b184f7c20b.png)

**Comment by you4jang** [comment]
@jar555 Thank you so much. I got a good app due to your advice.

**Comment by you4jang** [comment]
Hi, be-hase. Thank you for your kindness with pictures for me.

I wonder that how to send my messages using the bot to users as my friend. In order to send messages to a user as a friend, I had to know my friend's <user_id>. But <user_id> was not Line Messanger ID. It seems to be the special type. About it, @tokuhirom said, the way to get it is to get from the payload of the webhook.

I don't have a server which receives the information as webhook. So then, how can I get <user_id> from the payload of the webhook? Is there anyway? If I have a server which receives webhook, how can I get the special type of <user_id> that be used the Line Bot? For example, for **you4jang** of Line Messanger ID.

Thank you.

**Comment by be-hase** [comment]
(Something like) a server is necessary.

I will close this issue.
Thanks.
