### ISSUE TITLE
Developer Trial to Light Plan Questions

### ISSUE THREAD

**Issue by piontpiont** [line/line-bot-sdk-python#190]
Hello 

My Line Bot Account has been transfer from developer trial into light on 6/20.

I have 4 questions:
(1)If I use reply API, is it has max reply messages?
(2)How many time out seconds in reply API?
(3)LINE Messaging API has any function for prohibit to forward message?
(4)LINE Messaging API has any function for Screenshot?

**Comment by tkgauri** [comment]
@piontpiont 
For plan related queries, please submit your question here: https://www.linebiz.com/jp-en/
We will close this issue from here for now.
Thank you :)
