### ISSUE TITLE
Flex Message padding_all error

### ISSUE THREAD

**Issue by IlhamriSKY** [line/line-bot-sdk-python#211]
I made a flex message from the simulator, PaddinAll with json [source code json](https://pastebin.com/pW87ifiY) running normally, then I moved using the python line sdk padding_all [source code python](https://pastebin.com/RwGWUgVP) to become unused. I have checked several times and nothing seems to be different.
![26330](https://user-images.githubusercontent.com/18723904/66088809-bc6b6f00-e5a6-11e9-9aa2-780fa6b939e7.jpg)

**Comment by okue** [comment]
What version of `python-bot-sdk` do you use? Is it 1.14.0?
`paddingAll` is new feature of flex message.

**Comment by IlhamriSKY** [comment]
@okue  i am using heroku for testing and yes i am using line bot sdk version 1.14.0

![image](https://user-images.githubusercontent.com/18723904/66243194-dbe0d400-e72d-11e9-9c7b-013b0414b1c4.png)

**Comment by IlhamriSKY** [comment]
@okue My error is in the placement of pedding_all from python and padingAll from json.
they collide with each other.

**Comment by IlhamriSKY** [comment]
> 
> 
> What version of `python-bot-sdk` do you use? Is it 1.14.0?
> Since `paddingAll` is a new feature of flex message, sdk older than 1.14.0 does not support it.

@okue My mistake was in the application of the version that runs on Heroku, even though I was update using the latest version, but the one running was the first version that I installed, thanks for the help.
