### ISSUE TITLE
How to close bot in python?

### ISSUE THREAD

**Issue by Truth0906** [line/line-bot-sdk-python#214]
As title,
I don't know how to send a word to bot then close bot.

**Comment by tkgauri** [comment]
@Truth0906 ,
What do you mean by 
> close bot.

**Comment by Truth0906** [comment]
shutdown

**Comment by okue** [comment]
Sorry, It doesn't make sense to me.
What do you want to do?

**Comment by zarszz** [comment]
I think the bot shutdown depends on where your bot deployed

**Comment by Truth0906** [comment]
When I fixed a bug, I send restart to bot to reload new version code.
I write a start loop in batch like this.

@echo off
:loop
python Bot.py
go to loop

So the only problem is how to stop bot?

**Comment by ferdi554** [comment]
If you run your bot on your own server, to stop the process just CTRL + C and run your script again

**Comment by okue** [comment]
@Truth0906

line-bot-python-sdk only supports Messaging API and Webhook event parser.

line-bot-python-sdk is not related to how to manage your bot and bot server.

**Comment by Truth0906** [comment]
I understand.
Thanks a lot for reply.
