### ISSUE TITLE
TemplateSendMessage class init error, cause 400 error, and documentation miss match!

### ISSUE THREAD

**Issue by gogobook** [line/line-bot-sdk-python#226]
## Documentation miss match
The TemplateSendMessage example in developers documentation. The property "altText" miss match TemplateSendMessage class init property "alt_text". That will cause property "altText" be removed. and cause a 400 error_response={"details": [{"message": "May not be empty", "property": "messages[0].altText"}]

plz fix it!

**Comment by okue** [comment]
Sorry for the late reply.
What is _developers documentation_? Is this page https://developers.line.biz/en/reference/messaging-api/#template-messages ?

In line-bot-sdk-python, basically all properties are in snake case.
This example message works correctly without any errors.
https://github.com/line/line-bot-sdk-python#templatesendmessage---buttonstemplate

**Comment by gogobook** [comment]
Yes, in that page, you can see properties of python example is not snake case, it's camel case. Maybe developers documentations need to fix it. Is there some where I can ask that developer documentation to change it?

**Comment by okue** [comment]
Thank you for your reporting.
Could you show the url or the screenshot of the python example which is not correct?
I'll report it to Developers Documentations team.

**Comment by gogobook** [comment]
/home/lee/桌面/2019-11-30 17-25-27 的螢幕擷圖.png
/home/lee/桌面/2019-11-30 17-27-13 的螢幕擷圖.png
/home/lee/桌面/2019-11-30 17-27-32 的螢幕擷圖.png

**Comment by gogobook** [comment]
Thanks for your help.

**Comment by okue** [comment]
It seems this is not a python example, but just a JSON.
I think the tab (shell, java, ruby, ..., python, ...) is confusing.
I'll report it. (But, I don't know when that tab is modified)

Thanks for your reporting.
