### ISSUE TITLE
New property added to "sticker message" webhook event

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-python#228]
> We added a new stickerResourceType property to the webhook event that notifies you when a sticker message is sent.
> Use this property to see what type of sticker was sent (still image, animated sticker, sticker with sound, etc.).

Messaging api reference for [`sticker`](https://developers.line.biz/en/reference/messaging-api/#wh-sticker)
[News](https://developers.line.biz/en/news/#new-property-added-to-sticker-message-webhook-event-2019-12-05)

**Comment by okue** [comment]
Thanks @clsung.
