### ISSUE TITLE
Support stay event added to beacon event

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-python#231]
> In the Messaging API beacon event, a stay event has been added to indicate that the user is staying in the covered area of the beacon.

Messaging api reference: https://developers.line.biz/en/reference/messaging-api/#beacon-event
News: https://developers.line.biz/en/news/#a-stay-event-was-added-to-beacon-event-2019-12-06

**Comment by okue** [comment]
We don't have to do anything for this feature.
