### ISSUE TITLE
In the line channel, can we force user to submit his current location (without modified)?

### ISSUE THREAD

**Issue by kittiu** [line/line-bot-sdk-python#234]
Yes, currently, user can share location. But user also can change the location away from his/her current, before share.
Are there anyway to disallow that, i.e., use rich menu to share location possibe? Are there any where I could find the example?

Thanks!

**Comment by okue** [comment]
Sorry for the late reply.
Your question is about not `line-bot-sdk-python`, but Messaging API.
Please ask a question at [Developers Community site](https://www.line-community.me/questions).
