### ISSUE TITLE
Update FileMessage Attribute name to match 

### ISSUE THREAD

**Issue by wasdee** [line/line-bot-sdk-python#249]
## Problem
what `__repr__` show
![Screenshot 2020-03-25 at 11 19 43 PM](https://user-images.githubusercontent.com/8089231/77559759-224e0900-6eef-11ea-8ffc-37360c2c4da6.png)

what I expect
```python
event.message["fileName"] # or
event.message.fileName
```

but this is what to code
```python
event.message.file_name
```

for `fileSize` as well

**Comment by okue** [comment]
Do you suggest `__repr__` implementation should be modified so that it prints like this?
```
message: { file_name: ..., file_size: ..., ... }
```

**Comment by CircleOnCircles** [comment]
yes

**Comment by okue** [comment]
Thanks for opening the nice issue.

**Comment by o926428377** [comment]
Hello @CircleOnCircles,
The [pull request](https://github.com/line/line-bot-sdk-python/pull/252)  may meet your request.

**Comment by CircleOnCircles** [comment]
> Hello @CircleOnCircles,
> The [pull request](https://github.com/line/line-bot-sdk-python/pull/252) may meet your request.

Already check that so the PR allow dictionary-access e.g. `message['fileName']` Gj 👍 

There are 2 more things to consider.
1. `__repr__` now matched with  dictionary-access which is a nice thing 👍 
2. the dot access e.g. `message.file_name` is it consider an internal api? 

if it is, may be leave it as is or refactor the variable name to `message._file_name` to signal developers and IDE to not suggest that

else we might need another PR to 
1. refactor the name to `message.fileName`
2. do a monkey patch or `@property` for `message.fileName`

**Comment by o926428377** [comment]
> > Hello @CircleOnCircles,
> > The [pull request](https://github.com/line/line-bot-sdk-python/pull/252) may meet your request.
> 
> Already check that so the PR allow dictionary-access e.g. `message['fileName']` Gj 👍
> 
> There are 2 more things to consider.
> 
> 1. `__repr__` now matched with  dictionary-access which is a nice thing 👍
> 2. the dot access e.g. `message.file_name` is it consider an internal api?
There is  a good question, it could be answered by official Line developer.
I thought it might consider the [beautiful Python code](https://realpython.com/python-pep8/#naming-conventions).
> 
> if it is, may be leave it as is or refactor the variable name to `message._file_name` to signal developers and IDE to not suggest that variable.
> 
> else we might need another PR to
> 
> 1. refactor the name to `message.fileName` OR
> 2. do a monkey patch or `@property` for `message.fileName`
I have the idea that making a switch var to decide  attribute name format (fileName or file_name) in Message class.

**Comment by CircleOnCircles** [comment]
What is a 'switch var' in python like? I've never heard this before.

**Comment by o926428377** [comment]
> What is a 'switch var' in python like? I've never heard this before.
Oh sorry, it just named by myself.
It's mean a variable which could choose whether using the original attribute name.

**Comment by CircleOnCircles** [comment]
> Oh sorry, it just named by myself.
> It's mean a variable which could choose whether using the original attribute name.
> btw, I've committed it to #252

oh I see what you mean.  😉

**Comment by Yang-33** [comment]
resolved by https://github.com/line/line-bot-sdk-python/pull/252
