### ISSUE TITLE
Clarification on using Messaging API with Business Accounts

### ISSUE THREAD

**Issue by ompemi** [line/line-bot-sdk-python#25]
Today, we support the API of Business Accounts to create a bot (old BOT API): https://developers.line.me/businessconnect/development-bot-server and it works great. We refresh the tokens as it is specified in the documentation.

Now, we are integrating with Messaging API. Messaging API seems to not need to refresh any token unless you use the Social API, and I am not sure if we should still be using any of the Business Connect API endpoints.

Is the new Messaging API spec the standard for all accounts to create a bot?

**Comment by GuitarSucks** [comment]
Hi @ompemi 
When you are talking about 
> Business Accounts to create a bot (old BOT API)

Do you mean about the old BOT API Trial or are you talking about the our Business Connect ?

Anyways the facts are as below:

- Messaging API from Free to Pro plan, don't need to refresh token
- Messaging API Pro plan has ability to select short term token which is a 30 day token
- Messaging API for Business Connect plan, will require to use short term token which is also 30 day token

**Comment by ompemi** [comment]
@GuitarSucks As we are a platform, we support both: Bot API Trial (as far as I know, deprecated now) and Business Connect API (https://developers.line.me/businessconnect/development-bot-server).

Thanks for the documentation, we will then refresh tokens always. I would encourage to add docs on this on both LINE page and this repo.

Just to clarify, the API documentation for Business Connect is deprecated now? We are migrating to Messaging API entirely.

**Comment by bottsjw** [comment]
@GuitarSucks It would be great to see additional progress with the Messaging API. We see significant limitations with several missing/deficient functions that prevent us from fully using it.
"Join" and "Leave" are nearly unusable as they do not offer any way to see when and who leaves/enters a group. Further, being able to compile a list of MIDs for those in a group as well as identifying a message by MID sender is definitely needed in the API.
Any road map visibility for those using the new Messaging API?

**Comment by GuitarSucks** [comment]
Hi guys
Sorry for the delay.

@ompemi 
>Just to clarify, the API documentation for Business Connect is deprecated now?
It will be deprecated on end of January  2018. And sorry there might be small changes on Messaging API for Business Connect. Ill post it when we confirm.

@bottsjw 
Thank you. Im aware of such limitations and we are currently talking about it. For the road map Im hoping we can disclose some info to the public.
