### ISSUE TITLE
Support Channel access token v2.1

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-python#254]
https://developers.line.biz/en/news/2020/04/06/channel-access-token-apis-v2-1/

**Comment by tkgauri** [comment]
Update to Channel access token v2.1 apis has been released.

News: https://developers.line.biz/en/news/2020/06/22/new-channel-access-token-endpoint-and-deprecation/

**Comment by kassy11** [comment]
@tkgauri Is this Issue working? I need this change.

**Comment by tokuhirom** [comment]
Related issues:
- https://github.com/line/line-bot-sdk-java/pull/508
- https://github.com/line/line-bot-sdk-php/pull/295

**Comment by schwannden** [comment]
hello anybody working on this issue?

**Comment by louis70109** [comment]
Feature not implemented. Maybe someone could fork it and re-send a new PR?
