### ISSUE TITLE
Description of The Limit Number of Rich Menu Differs From the API Reference

### ISSUE THREAD

**Issue by loloicci** [line/line-bot-sdk-python#257]
## Documentation

README.rst describes

> You can create up to 10 rich menus for one bot.

https://github.com/line/line-bot-sdk-python/blob/master/README.rst#create_rich_menuself-rich_menu-timeoutnone

This description differs from API Reference

> You can create up to 1000 rich menus for one LINE Official Account with the Messaging API.

https://developers.line.biz/en/reference/messaging-api/#create-rich-menu

Which is the collect one?

**Comment by okue** [comment]
https://developers.line.biz/en/reference/messaging-api/#create-rich-menu is correct.

We have to correct README.rst.
