### ISSUE TITLE
I want to use get_group_summary function by installing line-bot-sdk

### ISSUE THREAD

**Issue by miyagin15** [line/line-bot-sdk-python#281]
I want to use get_group_summary function(https://github.com/line/line-bot-sdk-python/blob/master/linebot/api.py). But, I couldn't use it with line-bot-sdk installed thorough pypi.  
I think the line-bot-sdk (https://pypi.org/project/line-bot-sdk/) don't include get_group_summary function.
How can I use your get_group_summary function.

**Comment by okue** [comment]
`get_group_summary` is not released yet. https://github.com/line/line-bot-sdk-python/commit/995dab2b4b41d0eff77fa95708f5851949b16e36
That will be included in the next release version `1.17.0`.

Sorry for inconvenience.

**Comment by miyagin15** [comment]
Thank you for replying.
I am looking forward to using an amazing line-bot-sdk.
