### ISSUE TITLE
how bound-object work?

### ISSUE THREAD

**Issue by adhiartawika** [line/line-bot-sdk-python#282]
hello guys recently i been learning how to use the rich menu in line messanger api, it work but i am still confused how RichMenuBounds work and what is the x= and y= value used to position the rich area lets say i have rich menu size of width 800 and height 540 how can i divide it to 4 box? thanks

**Comment by okue** [comment]
Hi, thanks for using Messaging API and line-bot-sdk.
Issues opened here should be about `line-bot-sdk-python`.

Please ask a question about Messaging API at developers community page: https://www.line-community.me/questions 😃
