### ISSUE TITLE
Messaging API - August 2020 update

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-python#283]
News: https://developers.line.biz/en/news/2020/08/04/messaging-api-update-august-2020/

- [x] [Unsend event has been added](https://developers.line.biz/en/reference/messaging-api/#unsend-event)
- [x] [Video viewing complete event has been added](https://developers.line.biz/en/reference/messaging-api/#video-viewing-complete)
- [ ] [The audiences property is now optional instead of required for a certain endpoint](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group)
- [ ] [Create audience for uploading user IDs (by file)](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group-by-file)
- [ ] [Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by file](https://developers.line.biz/en/reference/messaging-api/#update-upload-audience-group-by-file)

**Comment by okue** [comment]
Unsend & Video play complete events will be implemented by #284.

**Comment by Yang-33** [comment]
will be implemented in https://github.com/line/line-bot-sdk-python/issues/431

**Comment by Yang-33** [comment]
resolved by https://github.com/line/line-bot-sdk-python/pull/432
