### ISSUE TITLE
Ignoring WebHook URL Verify message to avoid error

### ISSUE THREAD

**Issue by smatsumt** [line/line-bot-sdk-python#287]
## Problem

The LineBot cause error when we push "WebHook URL" - "Verify" button in LINE Developers console even if the handler is deployed successfully. This is because the test message contains invalid replyToken like this.

```
"replyToken": "00000000000000000000000000000000"
```

I think this is a little bit confusing behavior. For example, please check https://qiita.com/q_masa/items/c9db3e8396fb62cc64ed (Japanese)

## Solution

If we patch the SDK, we may check the event in the handler. If the event has replyToken for test purpose, it is treated as "test message", and not call normal handler added by SDK user.

**Comment by okue** [comment]
Sorry for inconvenience.
This issue that LINE server sends meaningless replyToken will be resolved internally.
Please wait for that time.
