### ISSUE TITLE
Environment variable.

### ISSUE THREAD

**Issue by policephp** [line/line-bot-sdk-python#29]
How to fix this?

Specify LINE_CHANNEL_SECRET as environment variable.

![cmd](https://cloud.githubusercontent.com/assets/25357248/22315615/7c5c8b44-e39a-11e6-9f21-1318f0208dc2.png)

My config like this

![cmd 2](https://cloud.githubusercontent.com/assets/25357248/22315630/8e62d64a-e39a-11e6-93f6-8cc2c41ad834.png)

**Comment by BigCandy** [comment]
channel_secret = YOUR_LINE_CHANNEL_SECRET
channel_access_token = YOUR_LINE_CHANNEL_ACCESS_TOKEN

**Comment by policephp** [comment]
@BigCandy ohh okay thx
