### ISSUE TITLE
Call keyboard from Rich menu and add more menu in chat bar text

### ISSUE THREAD

**Issue by albertchristian92** [line/line-bot-sdk-python#296]
1. Would it be possible to call keyboard from the rich menu button? Our goal is call the keyboard without click small keyboard icon on the corner.
2. How to modify chat bar text into another button ? Example is the images below

![image](https://user-images.githubusercontent.com/12479762/94580856-fb60fd00-02ac-11eb-8eda-4fd169bfe3c1.png)

**Comment by louis70109** [comment]
1. You mean if the user clicks the richmenu button and bot will trigger the keyboard open? if yes it couldn't. The richmenu just follow [those actions](https://developers.line.biz/en/reference/messaging-api/#action-objects).
2. No it's not, but you could modify the [chatBarText](https://developers.line.biz/en/docs/messaging-api/using-rich-menus/#create-a-rich-menu).

**Comment by albertchristian92** [comment]
Thank you very much for your reply. I will find another way to solve this.
