### ISSUE TITLE
Code in GitHub not in synced with PyPI

### ISSUE THREAD

**Issue by vsupacha** [line/line-bot-sdk-python#304]
## System Informations

* Python version: 3.7
* SDK version: 1.17.0
* OS: Windows 10

## Expected Behavior
New features in 1.17.0 should be active, e.g. get_bot_info()

## Current Behavior
Can not invoke get_bot_info() and all new APIs

## Steps to Reproduce

1. Create LineBotApi object with channel access token
1. Use get_bot_info() -> get error
1. Use dir( line_bot_api ) -> no get_bot_info() and all new methods
1. Check code in site-packages -> no new features

## Logs
`Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from linebot import LineBotApi
>>> bot = LineBotApi('NONE')
>>> dir(bot)
['DEFAULT_API_DATA_ENDPOINT', 'DEFAULT_API_ENDPOINT', '_LineBotApi__check_error', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_delete', '_get', '_post', 'broadcast', 'cancel_default_rich_menu', 'create_rich_menu', 'data_endpoint', 'delete_rich_menu', 'endpoint', 'get_default_rich_menu', 'get_group_member_ids', 'get_group_member_profile', 'get_group_members_count', 'get_group_summary', 'get_insight_demographic', 'get_insight_followers', 'get_insight_message_delivery', 'get_insight_message_event', 'get_message_content', 'get_message_delivery_broadcast', 'get_message_delivery_multicast', 'get_message_delivery_push', 'get_message_delivery_reply', 'get_message_quota', 'get_message_quota_consumption', 'get_profile', 'get_progress_status_narrowcast', 'get_rich_menu', 'get_rich_menu_id_of_user', 'get_rich_menu_image', 'get_rich_menu_list', 'get_room_member_ids', 'get_room_member_profile', 'get_room_members_count', 'headers', 'http_client', 'issue_channel_token', 'issue_link_token', 'leave_group', 'leave_room', 'link_rich_menu_to_user', 'link_rich_menu_to_users', 'multicast', 'narrowcast', 'push_message', 'reply_message', 'revoke_channel_token', 'set_default_rich_menu', 'set_rich_menu_image', 'unlink_rich_menu_from_user', 'unlink_rich_menu_from_users']`

**Comment by vsupacha** [comment]
Further information
1. Try using pip to uninstall, then install again -> not work
1. Try using pip to uninstall, then force pip to install directly from github -> ok
`python -m pip install git+https://github.com/line/line-bot-sdk-python/`

Verify results by checking source code directly.

**Comment by cryeo** [comment]
SDK version 1.17.0 does not support `get_bot_info` method. (See also PR #301 and [1.17.0 release note](https://github.com/line/line-bot-sdk-python/releases/tag/1.17.0))

If you want to use new features before official release, please install package from the repository as you mentioned above :)

**Comment by vsupacha** [comment]
@cryeo Thank you for your explanation. I just read details in README.rst and forgot to check release explanation. So I would like to close this issue.
