### ISSUE TITLE
NameError: name 'TextSendMessage' is not defined

### ISSUE THREAD

**Issue by chungsir** [line/line-bot-sdk-python#31]
i only want to use push mesagee
when i test push message

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    line_bot_api.push_message('u307947f4bsdfedff2sdf04c81f39a89ed07',TextSendMessage(text='Hello World!'))
NameError: name 'TextSendMessage' is not defined

what's problem 
thanks!

**Comment by be-hase** [comment]
Did you properly wrote `import` statements?

Ref:
Https://github.com/line/line-bot-sdk-python/blob/master/examples/flask-echo/app.py#L17-L30

**Comment by chungsir** [comment]
thank you 
but modiy it then 

Traceback (most recent call last):
  File "new_line.py", line 5, in <module>
    line_bot_api.push_message('0edff29004c81f39a89ed07',TextSendMessage(text='hello world'))
  File "C:\python\lib\site-packages\linebot\api.py", line 124, in push_message
    '/v2/bot/message/push', data=json.dumps(data), timeout=timeout
  File "C:\python\lib\site-packages\linebot\api.py", line 262, in _post
    self.__check_error(response)
  File "C:\python\lib\site-packages\linebot\api.py", line 271, in __check_error
    raise LineBotApiError(response.status_code, error)
linebot.exceptions.LineBotApiError: <LineBotApiError [The property, 'to', in the request body is invalid (line: -, column: -)]>


why?
thanks again

**Comment by be-hase** [comment]
Let's see the error message.
`The property, 'to', in the request body is invalid`

`to` value is invalid.
Where did you get the value  (`0edff29004c81f39a89ed07`)?

This issue is not related to this repository, so I will close this issue.

**Comment by be-hase** [comment]
The userId of the Messaging API starts with U (uppercase letters).
It is different from the previous API (such as BOT API Trial, LINE login V1).

ref:
https://business.line.me/news/20057478

**Comment by chungsir** [comment]
thanks a lot


it's ok
