### ISSUE TITLE
cannot reply as flex message

### ISSUE THREAD

**Issue by neroswords** [line/line-bot-sdk-python#314]
`linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=ba017fbc-07b2-46d6-a580-784923ce3e00, error_response={"details": [{"message": "invalid uri scheme", "property": "/hero/url"}], "message": "A message (messages[0])\u00a0in the request body is invalid"}, headers={'Server': 'openresty', 'Content-Type': 'application/json', 'x-line-request-id': 'ba017fbc-07b2-46d6-a580-784923ce3e00', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'x-frame-options': 'DENY', 'Expires': 'Mon, 25 Jan 2021 18:13:07 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 25 Jan 2021 18:13:07 GMT', 'Connection': 'close'}`

I got this error when I try to send flex message back to sender I have no idea what am I wrong because i'm new for line api, I need some help.
here was some part of my code

**flex message create func (give res some data)**
`def flexmessage():
    res = "test"

    if res == 'nodata':

        return 'nodata'

    else:

        productName,imgUrl,desc,cont = res

    flex = '''

    {

        "type": "bubble",

        "hero": {

          "type": "image",

          "url": "%s",

          "margin": "none",

          "size": "full",

          "aspectRatio": "1:1",

          "aspectMode": "cover",

          "action": {

            "type": "uri",

            "label": "Action",

            "uri": "https://linecorp.com"

          }

        },

        "body": {

          "type": "box",

          "layout": "vertical",

          "spacing": "md",

          "action": {

            "type": "uri",

            "label": "Action",

            "uri": "https://linecorp.com"

          },

          "contents": [

            {

              "type": "text",

              "text": "%s",

              "size": "xl",

              "weight": "bold"

            },

            {

              "type": "text",

              "text": "%s",

              "wrap": true

            }

          ]

        },

        "footer": {

          "type": "box",

          "layout": "vertical",

          "contents": [

            {

              "type": "button",

              "action": {

                "type": "postback",

                "label": "contact",

                "data": "%s"

              },

              "color": "#F67878",

              "style": "primary"

            }
          ]
        }

      }'''%(imgUrl,productName,desc,cont)
    return flex`

in my reply function
`flex = json.loads(flexmessage())
 print(flex)
 response = FlexSendMessage(
      alt_text='hello',
      contents=flex
  )
  print(response)

  line_bot_api.reply_message(Reply_token, response)`

**Comment by louis70109** [comment]
`{"message": "invalid uri scheme", "property": "/hero/url"}`
1. You need to check your hero block URL( `imgUrl` and `res` value)
