### ISSUE TITLE
why `sender_id` is deprecated? without substitude 

### ISSUE THREAD

**Issue by CircleOnCircles** [line/line-bot-sdk-python#315]
I wonder why this is deprecated. I searched thru all issues and prs. I found none mention about the reason.

I don't like the variable name of it  but, it is a **useful concept**. 

### instead of

doing a long a redundant check. which make code bit slower too due to if-else.

      if event.source.type == 'group':
          api.leave_group(event.source.group_id)
      elif event.source.type == 'room':
          api.leave_room(event.source.room_id)

### simply

elegant and faster

	api.leave_group(event.source.sender_id)

## new name

I would like to propose `source_id` instead of `sender_id` to signify better underlying value.

**Comment by louis70109** [comment]
As I see, `user` & `group` & `room` could let us know source type clearly and no confusion.
https://developers.line.biz/en/reference/messaging-api/#source-user

Maybe you can package them in your code?

**Comment by CircleOnCircles** [comment]
> As I see, `user` & `group` & `room` could let us know source type clearly and no confusion.
> [developers.line.biz/en/reference/messaging-api/#source-user](https://developers.line.biz/en/reference/messaging-api/#source-user)
> 
> Maybe you can package them in your code?

I agreed. already use them in that fashion.
