### ISSUE TITLE
sending pictures from local computer?

### ISSUE THREAD

**Issue by win20012** [line/line-bot-sdk-python#324]
From the doc, sending pictures need to be a HTTPS URL. If my picture is on the local computer, is there any way I can send the picture directly from my computer? or uploading picture to a picture hosting website is the only way. If so, are there any recommended websites that uploaded pictures that could delete pictures after certain time?

**Comment by louis70109** [comment]
Because the image just uses HTTPS URL.

As I see, you can use something like AWS S3, GCP Storage...etc, 
use API to upload an image which you would get an HTTPS URL back to your server.

Then you could send images.
