### ISSUE TITLE
Sporadic connection timeout and invalid reply token errors

### ISSUE THREAD

**Issue by ThiagoFJ** [line/line-bot-sdk-python#328]
When replying to LINE API webhook events via the `reply_message`, rarely a connection timeout error is throw followed by an invalid reply token error, as below:

```
[ERROR] ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2aadbe640>, 'Connection to api.line.me timed out. (connect timeout=5)'))
```

```
LineBotApiError: status_code=400, request_id=b024efd9-c856-4430-9c6c-7bb6248aa253, error_response={"details": [], "message": "Invalid reply token"}, headers={'Server': 'openresty', 'Date': 'Tue, 18 May 2021 02:35:11 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'x-line-request-id': 'b024efd9-c856-4430-9c6c-7bb6248aa253', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY'}
```

Initially I thought the reply token received via the webhook event could be getting corrupted somehow, but after some debugging and testing it does not seems to be the case. Also, it's strange that this error is always preceded by a connection timeout error. I'm unsure if the cause is actually a corrupt reply token or somehow the SDK / LINE API is handling the connection timeout as an invalid token.

Besides some issue on my implementation, could that error be caused by issues on the LINE Messaging API server or general internet issues?

**Comment by louis70109** [comment]
Hi, 

- do you have tried the same code in another OA for this case?
- could you provide your environment?

**Comment by ThiagoFJ** [comment]
> do you have tried the same code in another OA for this case?

Yes, I work with multiple OAs and I see the same issue happen sometimes.

> could you provide your environment?

Do you mean the environment where the code / SDK is running?

We use Lambda function via AWS service in a Python 3.8 environment.
**Flask** is used for the routing like the provided example code with **aswgi** module.

**Comment by louis70109** [comment]
From my experience, Lambda function has `cold start` time, meaning it needs to wake up a few time when Lambda be triggered. 
As I see, maybe it was `cold start` problem. (You can check for first-time webhook received)

**Comment by ThiagoFJ** [comment]
I don't think it's a `cold start` problem because we have a mechanism to keep the Lambda function warm by making a dummy call every 5 minutes. Looking at the execution logs, it always run below 1 seconds. We originally implemented because we would receive an error report mail from LINE every time the webhook lambda took more than 1 second to respond.

This webhook lambda then calls asynchronously another Lambda and quickly returns. The other Lambda then does the event processing and replies with appropriately by calling the SDK.

**Comment by louis70109** [comment]
Do you have a sample code and reproduce steps?
That we can find where is bottleneck together.
