### ISSUE TITLE
How to know what source which Line user add Line bot?

### ISSUE THREAD

**Issue by nguyendung17** [line/line-bot-sdk-python#329]
## Do this before creating an issue
We are working with Message API feature. My user can use line app then add our line bot to friend list by scan QR code.
We're printed QR code and stick them on information table in a school, office, subway station.
## Problem
When user add a line  bot to friend list, we don't know they added line bot from which QR code. 
## Solution
Somehow can we add some parameters to the QR code?

**Comment by louis70109** [comment]
You need a web page to control which user came here, then redirect to add friend page.

e.g. 

https://YOUR_DOMAIN.com?place=school -> catch `school` parameter and record it -> redirect https://line.me/R/ti/p/YOUR_OA_ID

Finally, you just print `https://YOUR_DOMAIN.com?place=school` as QR Code
