### ISSUE TITLE
Me need How to Create Richmenu Switch Action / Richmenu Alias pls

### ISSUE THREAD

**Issue by frame318** [line/line-bot-sdk-python#335]

**Comment by louis70109** [comment]
```
alias = RichMenuAlias(rich_menu_alias_id='richmenu-alias-b', rich_menu_id='richmenu-000000')
rich_menu_id = line_bot_api.create_rich_menu_alias(alias)
print(rich_menu_id)
```

Refs: https://developers.line.biz/en/news/2021/06/21/switch-between-multiple-rich-menus/

switch action will in the webhook `callback` : https://developers.line.biz/en/reference/messaging-api/#richmenu-switch-action

**Comment by frame318** [comment]
rich_menu_to_create = RichMenu(
    size=RichMenuSize(width=2500, height=843),
    selected=False,
    name="Nice richmenu",
    chat_bar_text="Tap here",
    areas=[RichMenuArea(
        bounds=RichMenuBounds(x=0, y=0, width=2500, height=843),
        action=URIAction(label='Go to line.me', uri='https://line.me'))] <<<
)
rich_menu_id = line_bot_api.create_rich_menu(rich_menu=rich_menu_to_create)
print(rich_menu_id)


How do I write an action? = 
{
   "type": "richmenuswitch",
   "richMenuAliasId": "richmenu-alias-b",
   "data":"richmenu-changed-to-b"
}

**Comment by frame318** [comment]
> 
> 
> ```
> alias = RichMenuAlias(rich_menu_alias_id='richmenu-alias-b', rich_menu_id='richmenu-000000')
> rich_menu_id = line_bot_api.create_rich_menu_alias(alias)
> print(rich_menu_id)
> ```
> 
> Refs: https://developers.line.biz/en/news/2021/06/21/switch-between-multiple-rich-menus/
> 
> switch action will in the webhook `callback` : https://developers.line.biz/en/reference/messaging-api/#richmenu-switch-action

rich_menu_to_create = RichMenu(
size=RichMenuSize(width=2500, height=843),
selected=False,
name="Nice richmenu",
chat_bar_text="Tap here",
areas=[RichMenuArea(
bounds=RichMenuBounds(x=0, y=0, width=2500, height=843),
action=URIAction(label='Go to line.me', uri='https://line.me'))] <<<
)
rich_menu_id = line_bot_api.create_rich_menu(rich_menu=rich_menu_to_create)
print(rich_menu_id)

How do I write an action? =
{
"type": "richmenuswitch",
"richMenuAliasId": "richmenu-alias-b",
"data":"richmenu-changed-to-b"
}
