### ISSUE TITLE
Cannot get line-bot-sdk >= 2.0.0 from pypi

### ISSUE THREAD

**Issue by CA-Lee** [line/line-bot-sdk-python#356]
As title, the currently lateset version on pypi (https://pypi.org/project/line-bot-sdk/) is 1.20.0 , is that anything I missed ? How should I do to install the latest version line bot sdk from pypi?

Thank you for taking care about this.

**Comment by louis70109** [comment]
Thanks for the report, we find the problem and will fix it.
