### ISSUE TITLE
Can I tag users in a group or room?

### ISSUE THREAD

**Issue by audi1** [line/line-bot-sdk-python#359]
I would like my bot to tag users in a group, similar to how we can manually do it using '@' key. Is this doable?

**Comment by louis70109** [comment]
It didn't support yet, but your bot can receive `mention event` in webhook object.

refs: https://developers.line.biz/en/reference/messaging-api/#wh-text

**Comment by audi1** [comment]
I saw some bots on line tag users in a group, how is that possible then?

**Comment by louis70109** [comment]
Maybe you see a real account but it was a bot.
