### ISSUE TITLE
Images do not show up on the desktop client

### ISSUE THREAD

**Issue by infinitylabs** [line/line-bot-sdk-python#36]
Ive properly formatted the images according to the API specs and images display perfectly fine on mobile, tablet, and chrome app versions of line but no desktop client on any platform is able to view images.

**Comment by be-hase** [comment]
Hi, @infinitylabs 
Could you tell me the URL of the image?

**Comment by infinitylabs** [comment]
Just for testing: https://uguu.it/Internet2.jpg

This is the exact same image taken from here in order to eliminate compression/size etc: https://upload.wikimedia.org/wikipedia/commons/d/da/Internet2.jpg

The file sends fine on chrome and mobile versions however all images never load on desktop. I assume it is either a ssl or cloudflare issue so Ive bypassed it by running all images through amazon s3, but its still annoys me it works on one client and not the other. Any help would be greatly appreciated!

**Comment by be-hase** [comment]
@infinitylabs 
Thank you for your reporting.
In my environment, it reproduced.

We will reply at a later date.

**Comment by Saixiii** [comment]
Any update ?
We still found the probelm

**Comment by mrmaakun** [comment]
This issue seems to be caused by a bug in the LINE desktop client. We plan to release a version of the client with this fixed sometime in June.
