### ISSUE TITLE
Drop python 3.6 support

### ISSUE THREAD

**Issue by tokuhirom** [line/line-bot-sdk-python#366]
https://pythonspeed.com/articles/stop-using-python-3.6/?fbclid=IwAR2jGWnfJk-WTS61kbaJTwbiONMN0BgvAiMrcMrmW9yvVvSIVI0F-rlK-3s

It becomes EOL in December 2021.

**Comment by corona10** [comment]
FYI, https://devguide.python.org/devcycle/
There is the official list of EOLs for each version.
(I expect that you may already know)
