### ISSUE TITLE
Multiple replies

### ISSUE THREAD

**Issue by hanifabd** [line/line-bot-sdk-python#368]
how to make multiple replies for 1 user message, i always got invalid reply token when i loop it. i've read that reply_token can only be used once. so how to tackle this kind of scenario?

**Comment by louis70109** [comment]
You can try following code for multiple replies:

```python
line_bot_api.reply_message(
        event.reply_token,
        [
           TextSendMessage(text='first text'),
           TextSendMessage(text='second text')
        ]
)
```
