### ISSUE TITLE
Line API Keep Telling me that my message is invalid, but I can't figure out what's wrong

### ISSUE THREAD

**Issue by R-N** [line/line-bot-sdk-python#38]
Here's the dump. It's a Carousel. I'm pretty sure its within the max length of anything and I provided everything that's not optional. Thanks

{"altText": "Choose who to kill by typing '/ww act <id> 3' by using the ids below\n8\t : Iklil Nur\n3\t : Rizqi Nur\n19\t : Juang\n7\t : A. M. Hafidz", "template": {"columns": [{"actions": [{"label": "Iklil Nur", "text": "/ww act 8 3", "type": "message"}, {"label": "Rizqi Nur", "text": "/ww act 3 3", "type": "message"}, {"label": "Juang", "text": "/ww act 19 3", "type": "message"}], "text": "Choose who to kill", "thumbnailImageUrl": null, "title": null}, {"actions": [{"label": "A. M. Hafidz", "text": "/ww act 7 3", "type": "message"}], "text": "Choose who to kill", "thumbnailImageUrl": null, "title": null}], "type": "carousel"}, "type": "template"}

The error message was "A message (messages[0]) in the request body is invalid"

**Comment by R-N** [comment]
The error message was "A message (messages[0]) in the request body is invalid"

**Comment by be-hase** [comment]
The number of actions should be consistent for all columns.
The first column has three actions, but the second column has only one action.

**Comment by R-N** [comment]
Damn. I didnt notice that it was written in the docs. Maybe cuz I keep trying to find my fault it in the table, haha.

Though, it would be better if Line API would tell me whats wrong with it instead of just saying that its wrong.

Thanks for your help :)

**Comment by be-hase** [comment]
I'm glad that your problem has been solved. :D
