### ISSUE TITLE
Filename error (.py%20) , Change to .py

### ISSUE THREAD

**Issue by NLGRF** [line/line-bot-sdk-python#405]
- I can't clone this repo for pr new example fastapi because Filename Error
Change
`https://github.com/line/line-bot-sdk-python/blob/master/tests/api/test_channel_access_token_v2_1.py%20`
to
`https://github.com/line/line-bot-sdk-python/blob/master/tests/api/test_channel_access_token_v2_1.py`

**Comment by louis70109** [comment]
Thanks
