### ISSUE TITLE
Can LineBot send GIF file to user?

### ISSUE THREAD

**Issue by momolly1024** [line/line-bot-sdk-python#422]
However, when I send gif file to user, It still show and send JPG file to user.

Is there anything I missed?

I use ImageSendMessage to send file.

```
ImageSendMessage(
                    original_content_url=i,
                    preview_image_url=i,
                )
```

**Comment by louis70109** [comment]
@momolly1024 you can use APNG by FlexMessage. [doc url](https://developers.line.biz/en/reference/messaging-api/#f-image)
