### ISSUE TITLE
Get content transcoding status and a preview image

### ISSUE THREAD

**Issue by YasSawada** [line/line-bot-sdk-python#426]
News URL
https://developers.line.biz/en/news/2023/02/14/messaging-api-updated/

- [Endpoint to verify the preparation status of a video or audio for getting](https://developers.line.biz/en/news/2023/02/14/messaging-api-updated/#preparation-status-20230214)
- [Endpoint to get a preview image of an image or video](https://developers.line.biz/en/news/2023/02/14/messaging-api-updated/#preview-20230214)

**Comment by Yang-33** [comment]
will be implemented in https://github.com/line/line-bot-sdk-python/issues/431

**Comment by Yang-33** [comment]
resolved by https://github.com/line/line-bot-sdk-python/pull/432
