### ISSUE TITLE
@All in the mention property of the webhooks

### ISSUE THREAD

**Issue by YasSawada** [line/line-bot-sdk-python#427]
News URL
[Messaging API now includes @All in the mention property of the webhooks](https://developers.line.biz/en/news/2023/03/08/messaging-api-updated/)

see the [Text](https://developers.line.biz/en/reference/messaging-api/#wh-text) section of [Message event](https://developers.line.biz/en/reference/messaging-api/#message-event)

**Comment by Yang-33** [comment]
will be implemented in https://github.com/line/line-bot-sdk-python/issues/431

**Comment by Yang-33** [comment]
resolved in https://github.com/line/line-bot-sdk-python/pull/432
