### ISSUE TITLE
[Question]  Combining TextSendMessage with PostbackAction to Open Keyboard Automatically

### ISSUE THREAD

**Issue by hunkim** [line/line-bot-sdk-python#433]
First of all, I want to express my appreciation for the line-bot-sdk-python; it's a fantastic tool!

I'm currently working on an AI ChatBot (https://liff.line.me/1645278921-kWRPP32q/?accountId=130glmtp) and utilizing the rich menu feature. 
![menu-ja](https://user-images.githubusercontent.com/901975/236649881-ed38cd5f-97e9-4679-89a1-13708b0c0b21.png)

When a user clicks on "新しい会話を始める," I want to send a message using the following code:

```python
line_bot_api.reply_message(
    event['replyToken'],
    TextSendMessage(text=str(msg), quick_reply=line_quick_reply))
```

However, I would also like to open the keyboard for the user simultaneously, without requiring any additional interaction from them. I believe this could be achieved by sending a postback action alongside the `TextSendMessage`.

Here's the postback action I've tried to implement:

```python
postback = PostbackAction(
    data='action=buy&itemid=1',
    inputOption='openKeyboard')  
```

Is it possible to send the TextSendMessage with the postback action together, so that the keyboard opens automatically for the user? Any guidance on how to achieve this would be greatly appreciated.

**Comment by Yang-33** [comment]
Without replying message, you can do this.
At first, you need to set postback action with `inputOption=openKeyboard` and `inputOption=someText` in your richmenu.
When you touch richmenu, keyboard is opened with filled some texts and shown richmenu is closed simultaneously.

**Comment by Yang-33** [comment]
About postback action, please read this! https://developers.line.biz/en/reference/messaging-api/#postback-action

**Comment by Yang-33** [comment]
@hunkim if you think it's resolved, please close this issue!
