### ISSUE TITLE
Is it possible to get the message "from the official Line account owner"?

### ISSUE THREAD

**Issue by CarolLiuXQ** [line/line-bot-sdk-python#435]
I know how to get the messgae from contacts', but I want to start to get messages when "I (official account owner) send messages to my contacts"?

This is the code for get the messages "from my contacts".
```
@app.route("/", methods=['POST'])
def linebot():
  body = request.get_data(as_text=True)
  try:
      signature = request.headers['X-Line-Signature']
      handler.handle(body, signature)
      data = json.loads(body)['events'][0]
      user_id = data['source']['userId']
```
This is the picture to image how the message I want to get.
![image](https://github.com/line/line-bot-sdk-python/assets/85448533/c3fa2f26-ae74-4b4a-808f-6fbf56d232da)

**Comment by chris911024** [comment]
`@app.route("/", methods=['POST'])
def linebot():
    body = request.get_data(as_text=True)
    try:
        signature = request.headers['X-Line-Signature']
        handler.handle(body, signature)
        data = json.loads(body)['events'][0]

      
        if data['type'] == 'message':
            # Get the user ID of the sender
            user_id = data['source']['userId']

        if user_id == 'your_official_account_user_id':
                
                message = data['message']['text']
                
    except Exception as e:
       
        print(str(e))

    return 'OK'
`

**Comment by chris911024** [comment]
`
@app.route("/", methods=['POST'])
def linebot():
    body = request.get_data(as_text=True)
    try:
        signature = request.headers['X-Line-Signature']
        handler.handle(body, signature)
        data = json.loads(body)['events'][0]

        # Check if the event type is a message
        if data['type'] == 'message':
            # Get the user ID of the sender
            user_id = data['source']['userId']

            # Check if the sender is the official account owner
            if user_id == 'your_official_account_user_id':
                # Process the message sent by the official account owner
                message = data['message']['text']
                # Do something with the message (e.g., store it, respond to it, etc.)

    except Exception as e:
        # Handle exceptions
        print(str(e))

    return 'OK'
`

**Comment by CarolLiuXQ** [comment]
@chris911024 
Thank you for your reply. But I want to get message from myside, not from the someone who send message to me.
我想要當我是官方帳號的管理者的時候，我手動訊息給我的user，我想要用這個手動送訊息給user的message來啟動我的message API，而不是從user送訊息給我開始的；因為你提供的code還是以當user傳訊息給我的時候才開始的接受訊息。

**Comment by CarolLiuXQ** [comment]
@louis70109 好的 謝謝QQ
