### ISSUE TITLE
openKeyboard is not working

### ISSUE THREAD

**Issue by ddkwing** [line/line-bot-sdk-python#438]
**Hi I have got a issue about openKeyboard.** 

my code
```
            RichMenuArea(
                bounds=RichMenuBounds(x=1666, y=843, width=834, height=843),
                action=PostbackAction(data="=key&itemid=666", inputOption="openKeyboard")
            )
```

**I make a handle to deal with the PostbackEvent, I can revice the postback_data in log.**

```
@handler.add(PostbackEvent)
def handle_postback(event):
    postback_data = event.postback.data

    if postback_data == "=key&itemid=666":
        print("postback_data: ", postback_data)
```

**My line version is 13.8**
I have read infos below, but not working either:
https://github.com/line/line-bot-sdk-python/issues/387
https://github.com/line/line-bot-sdk-python/issues/433
https://developers.line.biz/en/news/2022/05/13/richmenu-keyboard/

so please help me out, thank you very much.

**Comment by ddkwing** [comment]
I have fixed it, 

```
                action=PostbackAction(data="=key&itemid=666", inputOption="openKeyboard")
```

will be 
```
                action=PostbackAction(data="=key&itemid=666", input_option="openKeyboard")
```

**Comment by hunkim** [comment]
`input_option="openKeyboard"` fixes?
