### ISSUE TITLE
How are y'all deploying this? I can't figure out the syntax to deploy on heroku. I  would love any help to get a callback url to paste to collect user ids and push messages. Thank!

### ISSUE THREAD

**Issue by monhustla** [line/line-bot-sdk-python#46]
## Do this before creating an issue

- Check the [FAQ](https://github.com/line/line-bot-faq) for LINE bots
- Make sure your issue is **related to** the LINE Bot SDK. For general questions or issues about LINE bots, create an issue on the [FAQ](https://github.com/line/line-bot-faq) repository. Note that we don't provide technical support.

## When creating an issue

- Provide detailed information about the issue you had with the SDK
- Provide logs if possible

**Comment by be-hase** [comment]
I'm sorry. We don't support such a guide.
Please look at the below page, I think that there is hint.

* https://devcenter.heroku.com/categories/python
