### ISSUE TITLE
Difficulty parsing sources to gather my followers userids

### ISSUE THREAD

**Issue by monhustla** [line/line-bot-sdk-python#47]
I want to send a multicast message but can't figure out the syntax to do so.

I wanted to use WebHookParser but it's not being recognized when imported.

How could I do this using webhook handler?

Everytime I try:
'@handler.add(Source, message=TextMessage)
def handle_message(source):
    line_bot_api.multicast(
        event.source.userid,
        TextSendMessage(text="hey")`

I know that's obviously wrong for both multicast and push messages. I'm new to this and could use help on the syntax. It would be helpful to create a code that prints specific pieces of parsed data I ask for.

I have tried a lot of variations similar to the kitchensink example here: https://github.com/line/line-bot-sdk-python/blob/master/examples/flask-kitchensink/app.py

I have another script that will trigger the multicast message. I just don't know how to gather up all of my users ids.

Any help would be appreciated, thank you.

**Comment by be-hase** [comment]
> I just don't know how to gather up all of my users ids.

`LINE Messaging API` does NOT provides users who follow your BOT.
If you want to do that, you need to save the userId obtained in the follow event in the Database.

Thanks.
