### ISSUE TITLE
When Linebot sent a photo to user , then user click the phote. Can Linebot get the "coordinate" information of the click event to know where user click on the photo ?

### ISSUE THREAD

**Issue by weihsinyeh** [line/line-bot-sdk-python#484]

**Comment by Yang-33** [comment]
As far as I know, it's not supported in Messaging API. I can't find anything about this in https://developers.line.biz/en/reference/messaging-api/

**Comment by weihsinyeh** [comment]
> As far as I know, it's not supported in Messaging API. I can't find anything about this in https://developers.line.biz/en/reference/messaging-api/

OK!  I will try my best to find another way to implement the feature I want. Very thanks for your reply !

**Comment by Yang-33** [comment]
though I'm not sure your requirement, I think https://developers.line.biz/flex-simulator/ 's Hotel example provided in `Showcase` supports image + text by flex message. If you set text with postback action on the image, you can get which block(not coordinate, but it can be enough in some situation) LINE user clocks via webhook probably.

**Comment by weihsinyeh** [comment]
OK, thanks for your information!
