### ISSUE TITLE
Sent Photos Are Not Displaying for Those Using Data

### ISSUE THREAD

**Issue by monhustla** [line/line-bot-sdk-python#49]
I'm not entirely sure if this is the API or line settings.

I have an issue where a bot keyword triggers the bot to send a photo to the group. If the user is using solely data, the photo either displays an incorrect photo or doesn't load at all. The photos are displayed perfectly for those who are using wifi.

Is there any insight on this? I'm sure it could be a whole host of reasons. One odd thing is that screenshots and other photos sent manually by users are being displayed fine under data. It's only images sent by the bot that are causing problems.

Thanks for the help.

**Comment by krrrr38** [comment]
it seems network problem or something...?
could you open this kind of issue to [line/line-bot-faq](https://github.com/line/line-bot-faq), cause this is not related to python sdk.

**Comment by monhustla** [comment]
I'm not sure why this was closed. Issue #36  reported a very similar issue. It would be very helpful to know whether there is a fix coming for this or not @krrrr38

**Comment by krrrr38** [comment]
@monhustla
> could you open this kind of issue to line/line-bot-faq, cause this is not related to python sdk.

please talk about __python sdk__ in this repository.

**Comment by monhustla** [comment]
I was referring to the line bot python sdk, the method in which the images were sent...

However, you were correct. The fix was changing settings to auto-download for pictures.
