### ISSUE TITLE
Linebot v3 - 404 Not Found Error

### ISSUE THREAD

**Issue by tomyHHC** [line/line-bot-sdk-python#499]
I tried **linebot.model** and it works, which mean token and channel id are good.

However, when I switch to **linebot.v3**, it failed.

Here is the error log: https://busy-buffer-b46.notion.site/Python-linebot-v3-api-error-dc2806e1bda144df9795b00d3438efec?pvs=4

Does anyone know what's wrong with it?

**Comment by tokuhirom** [comment]
The exception is raised from here.
https://github.com/line/line-bot-sdk-python/blob/master/linebot/v3/webhooks/rest.py#L224

I can't understand what's happened. Since i can't see your code.
But i guess you may import wrong class from `linebot.v3.webhooks`.

Check your code again, and please take a look our sample code.
https://github.com/line/line-bot-sdk-python/blob/master/examples/flask-echo/app.py

**Comment by tomyHHC** [comment]
I would say my program is much like flask-kitchensink, using flask & line handler and webhook to serve Message API.

Here is part of the code. May you help me check? Appreciate!

from flask import Flask, request, abort
from linebot.v3.messaging import *
from linebot.v3.webhooks import *
from linebot.v3 import (
    WebhookHandler
)
from linebot.v3.models import (
    UnknownEvent
)
from linebot.v3.exceptions import (
    InvalidSignatureError
)

configuration = Configuration(access_token=linebot_token)

@handler.add(MessageEvent, message=TextMessageContent)
def handle_message(event):
    msg = event.message.text
    with ApiClient(configuration) as api_client:
        line_bot_api = MessagingApi(api_client)
        .
        .
        .

@app.route("/callback", methods=['POST'])
def callback():
    # get X-Line-Signature header value
    signature = request.headers['X-Line-Signature']

    # get request body as text
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)
    
    # handle webhook body
    try:
        handler.handle(body, signature)
    # except ApiException as e:
    #     app.logger.warn("Got exception from LINE Messaging API: %s\n" % e.body)
    except InvalidSignatureError:
        abort(400)

    return 'OK'

if __name__ == "__main__":
      port = int(os.environ.get('PORT', 5000))
      app.run(host='0.0.0.0', port=port)

**Comment by tokuhirom** [comment]
In general, using wildcard imports in python scripts can be problematic.
Especially in linebot.v3, another package contains a class with the same class name, so if you use wildcard imports, you may end up using a class from another package, so don't use it.

**Comment by tomyHHC** [comment]
> In general, using wildcard imports in python scripts can be problematic.
> Especially in linebot.v3, another package contains a class with the same class name, so if you use wildcard imports, you may end up using a class from another package, so don't use it.

You're right. After removing wildcard imports, it's good now!

Thank you so much. Appreciate it!



Another small question is how to postback QuickReplyItem action for **DatetimePickerAction/CameraAction/CameraRollAction/LocationAction**?

I can tell there is data in DatetimePickerAction, but it's string. How do we get the time user pick?

For CameraAction/CameraRollAction/LocationAction, I don't see there is data variable. only `type & label`.

For example:
```
class CameraAction(Action):
    """CameraAction.

    https://developers.line.me/en/reference/messaging-api/#camera-action

    This action can be configured only with quick reply buttons.
    When a button associated with this action is tapped,
    the camera screen in the LINE app is opened.
    """

    def __init__(self, label=None, **kwargs):
        """__init__ method.

        :param str label: Label for the action
        :param kwargs:
        """
        super(CameraAction, self).__init__(**kwargs)

        self.type = 'camera'
        self.label = label
```

**Comment by Yang-33** [comment]
https://github.com/line/line-bot-sdk-python/blob/7296de7119ecf61feb2299fcb08f7688488a0820/examples/flask-kitchensink/app.py#L627-L629 Please check [flask-kitchensink](https://github.com/line/line-bot-sdk-python/tree/7296de7119ecf61feb2299fcb08f7688488a0820/examples/flask-kitchensink). It's a good example to understand how to use it.

**Comment by Yang-33** [comment]
Camera action doesn't have `data` property. https://developers.line.biz/en/reference/messaging-api/#camera-action

**Comment by Yang-33** [comment]
(Close this issue if you think it's resolved!)

**Comment by tomyHHC** [comment]
I mean these items: **DatetimePickerAction/CameraAction/CameraRollAction/LocationAction**

How do we get data or PostbackAction from these items?
For example, how do we get date/datetime user select?

**Comment by Yang-33** [comment]
About CameraAction/CameraRollAction/LocationAction:
It doesn't have data property. Please read developers document https://developers.line.biz/en/reference/messaging-api/#camera-action.

About DatetimePickerAction: 
your application can receive postback webhook if user selects date/datetime.
Sample is here
- https://github.com/line/line-bot-sdk-python/blob/7296de7119ecf61feb2299fcb08f7688488a0820/examples/flask-kitchensink/app.py#L852-L865
- https://github.com/line/line-bot-sdk-python/blob/7296de7119ecf61feb2299fcb08f7688488a0820/examples/flask-kitchensink/app.py#L351-L369

and document is https://developers.line.biz/en/reference/messaging-api/#postback-event.

**Comment by tomyHHC** [comment]
> About CameraAction/CameraRollAction/LocationAction: It doesn't have data property. Please read developers document https://developers.line.biz/en/reference/messaging-api/#camera-action.
> 
> About DatetimePickerAction: your application can receive postback webhook if user selects date/datetime. Sample is here
> 
> * https://github.com/line/line-bot-sdk-python/blob/7296de7119ecf61feb2299fcb08f7688488a0820/examples/flask-kitchensink/app.py#L852-L865
> * https://github.com/line/line-bot-sdk-python/blob/7296de7119ecf61feb2299fcb08f7688488a0820/examples/flask-kitchensink/app.py#L351-L369
> 
> and document is https://developers.line.biz/en/reference/messaging-api/#postback-event.

thank you so much!
