### ISSUE TITLE
"line_bot_api.get_content" should be "line_bot_api.get_message_content" in official document

### ISSUE THREAD

**Issue by Tocknicsu** [line/line-bot-sdk-python#50]
https://devdocs.line.me/en/?python#content
In this document, the right side example python code 
```
message_content = line_bot_api.get_content('<message_id>')
```
I think it should be 
```
message_content = line_bot_api.get_message_content('<message_id>')
```
Ref: https://github.com/line/line-bot-sdk-python/blob/master/linebot/api.py#L182

**Comment by be-hase** [comment]
@Tocknicsu 
Thanks for your reporting. 👍 
We'll fix our document. :D

**Comment by be-hase** [comment]
We have fixed document. :D
(https://devdocs.line.me/ja/#content)
