### ISSUE TITLE
Cannot Retrieve image sent by line users.

### ISSUE THREAD

**Issue by Deen12520** [line/line-bot-sdk-python#51]
Situation:
I  sent a image to the bot that I built,but the bot cannot recv my image.

I use the method as follows:

```
message_content = line_bot_api.get_message_content(message_id)
file_path = "C:\workplace\ngrok-line-bot\message\image\1.png"
with open(file_path,'wb') as fd:
	for chunk in message_content.iter_content():
		fd.write(chunk) 
```               

Result:
the image cannot be sent and my bot also cannot recv.

----
I'm looking forward for your answer. Thank you :D

**Comment by be-hase** [comment]
@Deen12520 

Could you share some error information ? (e.g. error response, error stack trace, ...)

Or, How about you try curl request to confirm problem.
```
curl -X GET -H 'Authorization: Bearer YOUR_TOKEN' https://api.line.me/v2/bot/message/6481263546303/content -o image.png
```

**Comment by Deen12520** [comment]
Thank you. 
I can retrieve the image through the message_id.

but I have some questions, 
Where does the image save?
Does it save in the Line center?
