### ISSUE TITLE
how to create a multiline text in a textmessage

### ISSUE THREAD

**Issue by kanslor** [line/line-bot-sdk-python#513]
## Do this before creating an issue
want line bot reply a multiline text message

- Check our [developers documentation](https://developers.line.biz/en/docs/messaging-api/), [FAQ](https://developers.line.biz/en/faq/), and [developers community](https://www.line-community.me/questions) for more information on LINE bots and the Messaging API

## When creating an issue
is there any character or other stuff like `\n` can make a text line break

- Make sure your issue is **related to** the LINE Bot SDK. For general questions about LINE bots, please ask in https://www.linebiz.com/contact/

**Comment by Yang-33** [comment]
what text do you use? I think `\n` must work.
When I ran this in my local, message was shown as a multiline message.
``` python
line_bot_api.reply_message(
    ReplyMessageRequest(
        reply_token=event.reply_token,
            messages=[
                TextMessage(text='Multi\nLine')
            ]
    )
)
```

**Comment by kanslor** [comment]
OK，I test it again, it works， my original text use `\\n` ，shows `\n` in the final response text. Thanks for reply.
