### ISSUE TITLE
I've got error

### ISSUE THREAD

**Issue by socool** [line/line-bot-sdk-python#531]
## System Informations

* Python version: 3.8.17
* SDK version: line
* OS: MacOSX 13.4.1 (c) 

## Expected Behavior
I'll try to integrate line into rasa bot from this code
https://github.com/socool/rasa-line-connector/blob/master/addons/line_connector.py

## Current Behavior
when i was start server using this command 
```
rasa run -m models --credentials credentials.yml --enable-api
```
I've got error

## Steps to Reproduce
1. clone https://github.com/socool/rasa-line-connector
2. create line webhook and get credentials
3. create yaml with sample below
```
rasa:
  url: "http://localhost:5002/api"

addons.line_connector.LineConnectorInput:
  app_secret: "[APP_SECRET]"
  access_token: "[ACCESS_TOKEN]"
  ```
4. start rasa server 
```
rasa run -m models --credentials credentials.yml --enable-api
```

## Logs
```
  File "/Users/socool/.pyenv/versions/3.8.17/lib/python3.8/site-packages/linebot/webhook.py", line 139, in __init__
    self.signature_validator = SignatureValidator(channel_secret)
  File "/Users/socool/.pyenv/versions/3.8.17/lib/python3.8/site-packages/linebot/webhook.py", line 92, in __init__
    self.channel_secret = channel_secret.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by Yang-33** [comment]
Error said `channel_secret` is None, and it's passed by your program. It's not line-bot-sdk's bug.

**Comment by socool** [comment]
thank you
