### ISSUE TITLE
Difference between func() and func_with_http_info()

### ISSUE THREAD

**Issue by HappyGroupHub** [line/line-bot-sdk-python#537]
As the title of this question, I'm always curious about the difference between `func()` and `func_with_http_info()`.
Such like: `reply_message()` and `reply_message_with_http_info` function
I knew that they basically do the same thing but the one return with http info, anything else?
I mean which one is officially recommended? Is there any kind of use case that you must use the one with http info?

Sorry if this question sounds dumb lol
and Thanks for clarifying my doubt!

**Comment by Yang-33** [comment]
func: return only response body
func_with_http_info: return response body + status code + headers
