### ISSUE TITLE
emoji(Sticons) do not show up on the Line client

### ISSUE THREAD

**Issue by Deen12520** [line/line-bot-sdk-python#54]
## **problem**

Line user sends emoji(sticons) to my bot, and my bot return the same emoji(sticons). 
But, the emoji(sticons) cannot show up.

 It shows it's sysbol code, like (clov)(clov)(thinking of him)(Moon cool)

## **codes**
`
line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text= message_text))
`

## **logs**

`..."message":{"type":"text","id":"6521045438173","text":"(clov)(clov)(thinking of him)(Moon cool)"}}]}`

**Comment by Deen12520** [comment]
the sticons is the emoji.

**Comment by be-hase** [comment]
@Deen12520 
`(clov)` is emoji defined by LINE.

If you want to send these emoji, please refer to these document.
https://devdocs.line.me/en/#send-message-object

> You can include emoticons in your message text. Because emoticons are a part of Unicode, they must be converted from their character codes.
Note that the character code, 0x1000B2, is used in the example on the right. Although the emoticon does not show up correctly in the browser, it will show up in LINE.
For a list of emoticons that can be sent with the Messaging API, see emoticon list.

https://devdocs.line.me/files/emoticon.pdf
