### ISSUE TITLE
quote tokens的調用方式

### ISSUE THREAD

**Issue by s6601** [line/line-bot-sdk-python#565]
quote tokens的調用方式
https://developers.line.biz/en/docs/messaging-api/get-quote-tokens/
找不到對應方式使用回覆功能

**Comment by Yang-33** [comment]
We use a token when sending. Please refer to https://developers.line.biz/en/reference/messaging-api/#text-message. Request with `quoteToken` achieves you send message with quote feature.

If your question has been answered, please close the issue.

**Comment by Yang-33** [comment]
python sdk code is here https://github.com/Yang-33/line-bot-sdk-python/blob/f5ee25970ce0c4bfeedfddf214fb4390300e07ff/linebot/v3/messaging/models/text_message.py#L34
