### ISSUE TITLE
Adding new language support to documentation

### ISSUE THREAD

**Issue by AnerGcorp** [line/line-bot-sdk-python#586]
## Issue: Documentation Enhancement

**Introduction**
The `line-bot-sdk-python` project currently provides documentation primarily in English. To extend the reach and usability of this API, I propose adding support for Turkish and Russian languages.

**Details**
Adding Turkish and Russian translations would significantly benefit developers in respective countries, making the API more accessible and user-friendly for a wider audience. This could lead to increased usage and contributions from Turkish related regions like Turkey, Uzbek, Azerbaijan, Turkmenistan, also from Slavian related regions like Russian, Belarussia, Ukraine.

**Offer to Contribute**
I am willing to contribute by translating the existing documentation into Turkish and Russian. To accommodate this, we might consider structuring the documentation to support multiple languages. This could involve creating language-specific directories or files within the documentation repository.

**Conclusion**
Integrating Turkish and Russian support into the `line-bot-sdk-python` documentation could have a substantial positive impact on the community. I am eager to discuss this further and contribute to the translation.

Thank you for considering this enhancement.

**Comment by tokuhirom** [comment]
Thank you for your proposal to enhance the line-bot-sdk-python documentation with Turkish and Russian translations. Your willingness to contribute and the thoughtfulness of your suggestion are greatly appreciated.

After careful consideration, we have decided not to proceed with integrating additional language translations at this time. Our decision is based on the current priorities and resources of our project, which must be focused on maintaining and improving the core functionalities of the SDK. Adding support for multiple languages in documentation, while undoubtedly valuable, would significantly increase our maintenance burden and complexity at this stage.

We believe that keeping the documentation in English allows us to ensure its accuracy and consistency, especially as the SDK evolves. However, we recognize the importance of making our resources accessible to a broader audience and will keep your suggestion in mind for future consideration.

**Comment by AnerGcorp** [comment]
Thanks a lot for your consideration
