### ISSUE TITLE
How to save a GIF image in flask-kitchensink

### ISSUE THREAD

**Issue by purpledc** [line/line-bot-sdk-python#592]
i am use examples/flask-kitchensink/app.py
trying to save a GIF image in ImageMessageContent
but the fies save in JPG format.
how i can save it in GIF format?

**Comment by Yang-33** [comment]
as far as I know, bot can't receive GIF format, although LINE user sends image with GIF format. Thank you for your understanding.

**Comment by purpledc** [comment]
Thank you for your detailed reply. It seems that I can only save the image as a JPG format. Thank you again for your help.
