### ISSUE TITLE
How to used ClipboardAction？

### ISSUE THREAD

**Issue by dalnel** [line/line-bot-sdk-python#610]
I want add ClipboardAction in Buttons Template ，but  it is not work，my code:

```
from linebot.v3.messaging.models import ClipboardAction
from linebot.models import ButtonsTemplate, MessageAction, TemplateSendMessage, CarouselTemplate,  CarouselColumn, PostbackAction, URIAction

def delet_CarouselTemplate():
    columns=[]
    column_item = ButtonsTemplate(
        title="copy test",
        text="click button to copy text",
        actions=[
            ClipboardAction(
                type="clipboard",
                label="copy",
                clipboardText="copy hellow word"
            )
        ]
    )
    columns.append(column_item)
    return TemplateSendMessage(
        alt_text='ButtonsTemplate',
        template=ButtonsTemplate(columns)
    )
CarouselTemplate = delet_CarouselTemplate()
line_bot_api.reply_message(tk,CarouselTemplate)
```

I used breakpoints in VS Code to inspect what was happening, and I found out that this action was not even added. So, I checked the linebot.models, and I realized that ClipboardAction is not included there. Did I use the wrong method or did I forget to add it?

![image](https://github.com/line/line-bot-sdk-python/assets/53857925/1e32eee8-75bc-47f3-a78a-f2b1069003d9)

**Comment by YrChen1001** [comment]
I can't use this action either

**Comment by Yang-33** [comment]
Hi @YrChen1001, thank you for using line-bot-sdk-python. 
Please import definition from `linebot.v3.messaging.models` instead of `linebot.models`. `linebot.models` are too old. I'll deprecate them.

**Comment by Yang-33** [comment]
https://github.com/line/line-bot-sdk-python/blob/12360f822d966c7790a7f109b04db579107c443e/examples/flask-kitchensink/app.py#L303-L322 shows how to use `ButtonsTemplate` in  `linebot.v3.messaging.models`, that might help you!
