### ISSUE TITLE
Create new example for an echo-bot using AWS Lambda Functions, `linebot.v3`

### ISSUE THREAD

**Issue by 1chooo** [line/line-bot-sdk-python#627]
## Problem
Recently, while developing a Line Bot and working with AWS services, I noticed a lack of examples using `linebot.v3` with AWS Lambda Functions. Therefore, I've created a Line Bot architecture using AWS Lambda Functions in a serverless setup. Below is the architecture diagram.

![arch](https://github.com/line/line-bot-sdk-python/assets/94162591/1e8c5585-bb1a-48b8-9750-4503ab7a2c98)

### Source Code

```python
import json
import os

from linebot.v3 import WebhookHandler
from linebot.v3.messaging import (ApiClient, Configuration, MessagingApi,
                                  ReplyMessageRequest, TextMessage)
from linebot.v3.webhooks import MessageEvent, TextMessageContent


configuration = Configuration(access_token=os.getenv('CHANNEL_ACCESS_TOKEN'))
handler = WebhookHandler(os.getenv('CHANNEL_SECRET'))

@handler.add(MessageEvent, message=TextMessageContent)
def handle_message(event):
    with ApiClient(configuration) as api_client:
        line_bot_api = MessagingApi(api_client)
        
        line_bot_api.reply_message_with_http_info(
            ReplyMessageRequest(
                reply_token=event.reply_token,
                messages=[TextMessage(text=event.message.text)]
            )
        )

def lambda_handler(event, context):
    try: 
        body = event['body']
        signature = event['headers']['x-line-signature']
        handler.handle(body, signature)
        return {
            'statusCode': 200,
            'body': json.dumps('Hello from Lambda!')
        }
    except Exception as e:
        return {
            'statusCode': 500,
            'body': json.dumps(str(e))
        }
```

## Solution

I will submit pull requests to create the new **example** -- `aws-lambda-echo/` along with the necessary documentation. Additionally, I will include the `requirements.txt` file and a comprehensive `README.md`.

## What I've done?

Check the post I've write on my medium, and it's the traditional Chinese Version 👉🏻 [AWS: 用 AWS Lambda Function 開發 Serverless Line Bot — 1](https://medium.com/@1chooo/aws-%E7%94%A8-aws-lambda-functions-%E9%83%A8%E7%BD%B2-serverless-line-bot-1-8be9edca1447)

### Demo

![demo](https://github.com/line/line-bot-sdk-python/assets/94162591/d3560e4a-081e-4f61-bf4c-9cb8028d1bad)

If it's convenient, you can also assign this feature to me so that I can contribute to the `line-bot-sdk-python` development.

Thanks, Hugo

**Comment by mokuzon** [comment]
@1chooo Apologies for the delay in responding. Thank you for your suggestion.

I'm sorry, but we do not intend to add more samples at present. Increasing the number of samples would increase maintenance costs, and the proposed samples are not significantly different from the existing samples.
