### ISSUE TITLE
the function about rich menu, which one I need to used when I want to set the image for a rich menu?

### ISSUE THREAD

**Issue by ArthurTech123** [line/line-bot-sdk-python#644]
I'm trying to refactor my code from version 2 to version 3. 

However, when I attempt to set the rich menu menu image, 

I can't find a function equivalent to `line_bot_api.set_default_rich_menu` in the object of `messaging_api`. 

The sample code on GitHub also does not show any rich menu-related functionalities. 

Am I looking at the wrong object?

**Comment by habara-k** [comment]
Sorry for the delayed response. 
You can check it here: https://github.com/line/line-bot-sdk-python/blob/3fc854abd1e2b1eaefdef43b61d989af338007d6/linebot/v3/messaging/docs/MessagingApi.md#set_default_rich_menu.
