### ISSUE TITLE
Is it possible to get userId from rich menus?

### ISSUE THREAD

**Issue by DableUTeeF** [line/line-bot-sdk-python#671]
The Messaging API docs [here](https://developers.line.biz/en/reference/messaging-api) only shows fixed URI action. If I want to assign userId to each click I currently have to give 1 rich menu to each user. And I only have 1000 rich menus per account total.

Is it even possible to get the userId from click alone?

**Comment by mokuzon** [comment]
Thanks for using our product!

The action you can specify for the rich menu in the Messaging API is https://developers.line.biz/en/reference/messaging-api/#action-objects, and there is no action for user IDs like the one you are talking about.
