### ISSUE TITLE
some user or group id is None

### ISSUE THREAD

**Issue by mao-shonen** [line/line-bot-sdk-python#70]
First of all, I'm sorry my English is very bad

My bot gets some user or group id is None
This error is not accidental
None values for users or groups are always None
This problem caused me to be unable to identify who my users are

**Comment by okdtsk** [comment]
Hi! Could you show me your code snippet of your line bot as far as you can?
(Of course please mask your credentials like api token or secret key, blah blah blah... :))

**Comment by mao-shonen** [comment]
``` python
import os
import time
from requests import post

from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import *

app = Flask(__name__)
handler = WebhookHandler(os.environ.get('ChannelSecret'))
bot = LineBotApi(os.environ.get('ChannelAccessToken'))
server_url = os.environ.get('server_url')

@app.route("/callback", methods=['POST'])
def callback():
    balabala.....

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    print('%s <<< %s' % (event.source, event.message.text))

    if event.source.type == 'user':
        url = server_url + '/user'
    elif event.source.type == 'group':
        url = server_url + '/group'
    elif event.source.type == 'room':
        url = server_url + '/group'
    data = get_source(event)
    data['message'] = event.message.text
        
    r = post(url, json=data)
    if r.ok:
        reply_message = r.json()['reply_message']
        if type(reply_message) == str:
            reply_message = [reply_message]

        reply_message_object = []
        for msg in reply_message:
            if msg[:4] == 'http':
                msg = msg.strip()
                reply_message_object.append(ImageSendMessage(original_content_url=msg, preview_image_url=msg))
            else:
                reply_message_object.append(TextSendMessage(text=msg))

        print('%s >>> %s' % (reply_message, event.source))
        bot.reply_message(event.reply_token, reply_message_object)
```

This script runs on heroku
But the problem has occurred on line 22
> print ('% s <<<% s'% (event.source, event.message.text))

**Comment by okdtsk** [comment]
I try to run your code in my development environment (with some modifications around post request to your server), and it works without any problem.
Could you show me your error log on your heroku?

**Comment by mao-shonen** [comment]
![default](https://user-images.githubusercontent.com/22576780/31201749-6a2fea06-a992-11e7-910c-1f70b28e32b0.jpg)

**Comment by okdtsk** [comment]
Ok you mean your bot gets `user_id` as `None` even `group_id` is set when your bot receives a message from some users (not all), right?

Any LINE user can decline our [Official Accounts Terms of Use](https://developers.line.me/en/docs/messaging-api/user-consent) and if a user does not agree to it the bot cannot get the user's id.
Even in this case you can get group id and reply token to reply some message to source group.

So the user sent a message to you bot on heroku at 2017-10-04T18:30:12 & 18:32:39 may decline above terms of use.

You can find the document about event source of group/room here.
https://developers.line.me/en/docs/messaging-api/reference/#source-group

**Comment by mao-shonen** [comment]
I thought that only can not get user's name, status and other information
ok... I understand

Although i just do different responses to different users in the group
I think it is not a good idea to force all users to add my bot friend

anyway, thanks you
I know how to deal with it

**Comment by okdtsk** [comment]
Sorry for late response here @mao-shonen.
The null value of group id is same reason as above.

**Comment by fairuzi10** [comment]
@okdtsk I got this problem right now. While I know the reason of the absence of userId, I still have no idea about groupId. Isn't terms of use only for user, not group?
