### ISSUE TITLE
Content Bot for Home posts

### ISSUE THREAD

**Issue by Steffy17** [line/line-bot-sdk-python#71]
Hello,

I'm new to working with Line, but I want to create a Bot that can read the Home messages (public profile) of a user and eventually can download those contents. I looked through the Messaging API and Social API but couldn't find anything related to the home profile. So my questions are can I handle the home page as a room/channel? Are there any related information that could help me with this project or is the idea entirely impossible?

I really appreciate any help you can provide.

**Comment by be-hase** [comment]
Hi.

What is `Home messages`? Do you mean `Timeline` ?
LINE BOT cannot handle timeline information. Sorry.

**Comment by 120687** [comment]
[accountpage_PC_guide (1).pdf](https://github.com/line/line-bot-sdk-python/files/1416760/accountpage_PC_guide.1.pdf)
