### ISSUE TITLE
I have 2 problem from webhook

### ISSUE THREAD

**Issue by bique14** [line/line-bot-sdk-python#73]
1. webhook url verify success
but I'm not know that how I get userID like https://devdocs.line.me/en/#bot-api-get-profile

2. if I write /callback that 

```python
@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']

    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)
    
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)

    return 'OK'
```

## Bot is running normal. but webhook url can't verify
and when I insert method 'GET' into /callback  ..

```python
@app.route("/callback", methods=[**'GET',**'POST'])
def callback():
    signature = request.headers['X-Line-Signature']

    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)

    if request.method=='GET':
        return 'ok get'
    elif request.method=='POST':
        return 'ok post'

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)

    return 'OK'
````

## Bot is not running but webhook url can verify success.

I so confuse :(

Please help me. Thanks.

**Comment by okdtsk** [comment]
HI, sorry for late response.
Could you tell us your way how to verify and error log if it was produced.
Thanks.

**Comment by laymonage** [comment]
It seems that you can't use the "Verify" button in console if you call the Reply API.

Using the same code as written in `README.rst`:
```python
from flask import Flask, request, abort

from linebot import (
    LineBotApi, WebhookHandler
)
from linebot.exceptions import (
    InvalidSignatureError
)
from linebot.models import (
    MessageEvent, TextMessage, TextSendMessage,
)

app = Flask(__name__)

line_bot_api = LineBotApi('YOUR_CHANNEL_ACCESS_TOKEN')
handler = WebhookHandler('YOUR_CHANNEL_SECRET')


@app.route("/callback", methods=['POST'])
def callback():
    # get X-Line-Signature header value
    signature = request.headers['X-Line-Signature']

    # get request body as text
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)

    # handle webhook body
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)

    return 'OK'


@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text=event.message.text))


if __name__ == "__main__":
    app.run()
```

or the [`flask-echo`](https://github.com/line/line-bot-sdk-python/blob/master/examples/flask-echo/app.py) example app, verifying the Webhook in Console always returns the error saying that the server returns an invalid response.
However, deleting
```python
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text=event.message.text))
```
will make the verification successful, but of course the bot won't do anything when it receives a message.

In your example, the callback function will return `'ok get'` (or `'ok post'`, I don't know why you wrote this) and exit right away, therefore `handler.handle(body, signature)` won't be processed and Reply API won't be called, and Webhook verification will succeed.


Question is:
Is it possible to do Webhook verification AND calling the Reply API at the same time?
(I think this is related to https://github.com/line/line-bot-sdk-python/issues/37).

**Comment by mgilangjanuar** [comment]
Hmm I'll try to propose an idea to fix this issue. Currently, my work #80 still has build failed in CI.

**Comment by trumad** [comment]
I am also facing this issue. The bot will not join any group chat without webhook working properly, as well as the verify button not working properly in the development console. Would be great if this could be fixed!

**Comment by be-hase** [comment]
Because the replyToken and userId contained in the verify button are dummy data, if you use API to call it, it becomes error.
This button is used for confirming the connection. (Including SSL setting)

**Comment by trumad** [comment]
To clarify, you think that only the Verify button is broken and webhook does actually work? Is there another reason the bot won't join group chats? And why does the verify button work for the java version of the bot's sdk, but not the python sdk?

**Comment by be-hase** [comment]
> Is there another reason the bot won't join group chats?

Could you check this setting ?
(Default is `Disabled`)

<img width="867" alt="2018-01-10 15 32 31" src="https://user-images.githubusercontent.com/903482/34758754-8dc95eae-f61b-11e7-88c2-91fbfe1273b7.png">

> And why does the verify button work for the java version of the bot's sdk, but not the python sdk? 

Java SDK(with spring-boot) handles exception and always return 200.
If you want to do the same action in python, please handle the exception as follows.

```python
@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']

    # get request body as text
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)

    try:
        events = parser.parse(body, signature)
        for event in events:
            if not isinstance(event, MessageEvent):
                continue
            if not isinstance(event.message, TextMessage):
                continue

            line_bot_api.reply_message(
                event.reply_token,
                TextSendMessage(text=event.message.text)
            )
    except:
        # handle all exception
        print("Unexpected error:", sys.exc_info()[0])

    return 'OK'
```

**Comment by mgilangjanuar** [comment]
@trumad alternatively, you can install with `pip install -e git+https://github.com/mgilangjanuar/line-bot-sdk-python.git@master#egg=line_bot_sdk`  😆✌️

**Comment by trumad** [comment]
Thanks guys for your quick replies. The bot is enabled for joining group chats, yes. I'll hopefully get a chance to work on this project again tomorrow night given this new information. Thanks!

**Comment by jayhot1** [comment]
@be-hase i need your help i've emailed you my problem, can you please contact me ??
