### ISSUE TITLE
Repeated error message.

### ISSUE THREAD

**Issue by doodspav** [line/line-bot-sdk-python#77]
I started from a fresh LAMP stack on Ubuntu 16.04, updated it and installed the latest version of pip.
Then I installed the line bot sdk, and all the requirements.
I made a new file, test.py and copy pasted the echobot script into it, changing the channel access token and secret. I also changed the app.run() to app.run(host="myip",port=443) since the webhook url i gave was https://myip:443/.
I ran this, and repeatedly got the same error code:

```
203.104.146.154 - - [22/Nov/2017 02:44:07] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x03\x00\x82\x01\x00\x00~\x03\x03Z\x14\xe4w\xca\x12\xc4$\xae\xaa\xcb\x02\x1bF*\xa2S/\x11\xcd\\w\x0e~.\x03\xb2')
203.104.146.154 - - [22/Nov/2017 02:44:07] "▒~Z▒w▒▒$▒▒▒*▒S/▒\w~.▒
                                                                 ▒6▒,▒+▒/▒▒▒/5E" 400 -
```

Not quite sure what to do tho, and any help would be appreciated.

**Comment by Sung-eon** [comment]
1. LINE API requires developers to use SSL as default security policy. Did you set SSL certificates for your fresh LAMP stack? I'm using Flask with Let's Encrypt certificate, OpenSSL. 

2. I'm not sure host name you set on your server is correct or not. Try to change your host address as "0.0.0.0".

**Comment by doodspav** [comment]
so i was a moron, i forgot to install my SSL certificate, now i have it, but i get this error when i run the bot (also i changed the host in app.run to host="0.0.0.0")

  File "test.py", line 45, in <module>
    app.run(host="0.0.0.0",port=443)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 593, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 418, in __init__
    self.server_activate()
  File "/usr/lib/python2.7/SocketServer.py", line 440, in server_activate
    self.socket.listen(self.request_queue_size)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

any thoughts?
also honestly is there any chance u can just tell me what you did? simply because i spent like 5h trying t solve this erno last time lol 
also thnx for replying so fast before

**Comment by be-hase** [comment]
Please read error messages.

```
socket.error: [Errno 98] Address already in use
```

It seems that your server has already listened to that port.

**Comment by Sung-eon** [comment]
1. **socket.error: [Errno 98] Address already in use**
I think this one is the one of your server problem. Some application already uses port 443. Don't forget "one port for one app". If the other app on your server uses port 443 as secure HTTPS connection. You'd better set your port in line.py as other port (like 5000, which I'm using now)

2. You should add line for SSL connection in line.py. Please refer to below sample code.

3. The following is real code of mine, which is now on running. Some point where I think It's important is changed to English. (I'm Korean)
``
# To implement SSL
from OpenSSL import SSL

# Webhook 및 REST 통신을 위해 로딩 
from flask import Flask, request, abort

# LINE API // 귀찮으므로 전부 다 Importing
from linebot import (
    LineBotApi, WebhookHandler
)
from linebot.exceptions import (
    InvalidSignatureError
)
from linebot.models import (
    MessageEvent, TextMessage, TextSendMessage,
    SourceUser, SourceGroup, SourceRoom,
    TemplateSendMessage, ConfirmTemplate, MessageTemplateAction,
    ButtonsTemplate, ImageCarouselTemplate, ImageCarouselColumn, URITemplateAction,
    PostbackTemplateAction, DatetimePickerTemplateAction,
    CarouselTemplate, CarouselColumn, PostbackEvent,
    StickerMessage, StickerSendMessage, LocationMessage, LocationSendMessage,
    ImageMessage, VideoMessage, AudioMessage, FileMessage,
    UnfollowEvent, FollowEvent, JoinEvent, LeaveEvent, BeaconEvent
)

import json
import subprocess
import re

# Flask 구현
app = Flask(__name__)

# LINE TOKEN

line_bot_api = LineBotApi(Token)
handler = WebhookHandler(Secret)

# This Line.py is used by me exclusively
user = 'My User ID' 

# Webhook 부분
@app.route("/callback", methods=['POST'])
def callback():
    # get X-Line-Signature header value
    signature = request.headers['X-Line-Signature']
    
    # get request body as text
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)
    
    # handle webhook body
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    
    return 'OK'

# 암호화 없이 평문으로 전달하는 미개한 방식이기에 SHA-256 사용법을 알면 수정할 예정
# 서버 내부에서 통신을 하기 위해서 사용되는 부분
# SSL 인증서 때문에 당분간은 외부 접속을 통해 REST 명령을 주고 받기로 결정 (어차피 POST 명령 전달정도면 돈 얼마 안듬)
@app.route("/internal", methods=['POST'])
def webhook():
    
    # REST에서 POST로 명령을 전달받을때에는 Header로 다음에 취할 행동을 구분
    Take_action = request.headers['demanded_action']

    # 통신 내용은 JSON으로, 푸쉬 메시지로 보낼 부분은 Sending Message의 Value 값을 사용
    body = request.get_json()
    body = body['Sending Message']
    app.logger.info("Request body: " + str(body))
    
    # Torrent 관련
    if Take_action == str('torrent_start'):
        line_bot_api.push_message(user, TextSendMessage(text='Torrentのダウンロードが間もなく始まりますわ。' ))
        line_bot_api.push_message(user, TextSendMessage(text=body))
    elif Take_action == str('torrent_no'):
        line_bot_api.push_message(user, TextSendMessage(text='使えるTorrentがございませんね'))
    elif Take_action == str('torrent_complete'):
        line_bot_api.push_message(user, TextSendMessage(text='Torrentのダウンロード作業が終わりました。 ' ))
        line_bot_api.push_message(user, TextSendMessage(text=body))
    elif Take_action == str('torrent_upload'):
        line_bot_api.push_message(user, TextSendMessage(text='Torrentの整理が完了致しました。 ' ))
        line_bot_api.push_message(user, TextSendMessage(text=body))
    
    # 날씨 관련

    elif Take_action == str('weather_alert'):
        body = str(body[0])
        line_bot_api.push_message(user, TextSendMessage(text='気象特報ですわ。' ))
        line_bot_api.push_message(user, TextSendMessage(text=body))
    elif Take_action == str('weather_today_instant'):
        body = str(body[0])
        line_bot_api.push_message(user, TextSendMessage(text='今日のカンタン気象情報でございます。' ))
        line_bot_api.push_message(user, TextSendMessage(text=body))

    # 11번가 관련

    elif Take_action == str('11st_result'):
        line_bot_api.push_message(user, TextSendMessage(text='11번가 검색 결과입니다.' ))
        keyword = body[0]['검색 키워드']
        avg_price = body[0]['평균 가격']
        line_bot_api.push_message(user, TextSendMessage(
            text='お探しの{0}は見つかりました。平均価格は{1}ですね。'.format(keyword,avg_price)))
    
    return 'OK'

# Webhook을 통해 들어온 메시지에 답장하는 부분
@handler.add(MessageEvent, message=TextMessage)
def handle_text_message(event):
    text = event.message.text

    # subprocess를 사용한 이유는 os.system 사용시 python 스크립트를 실행하고 원래 서버로 돌아오지 않는 현상이 발생되어서 보안에 취약하지만 사용.
    
    # Torrent 관련
    if text == '토렌트 시작':
        line_bot_api.reply_message(event.reply_token, TextSendMessage(text="少々お待ち下さい"))        
        subprocess.Popen(['python3', '/directory'])
    elif text == '토렌트 정리':
        line_bot_api.reply_message(event.reply_token, TextSendMessage(text="ファイルをキッチリと片付けて見せますわ。"))        
        subprocess.Popen(['python3', '/directory'])

    # Plex 관련
    # Plex Media Server에 전달할 라이브러리 스캔 명령어
    elif text == '플렉스' or text == 'plex':
        line_bot_api.reply_message(event.reply_token, TextSendMessage(text="適当なボンタンを準備しますね。"))
        line_bot_api.push_message(user,TemplateSendMessage(
            alt_text='Plex Media Serverでスキャンするライブラリーを選んでください。',
            template=ButtonsTemplate(
            thumbnail_image_url='my server addrsss',
            title='ライブラリー選択',
            text='以下のボタンを一つを選んでみて下さい',
            actions=[
                URITemplateAction(
                    label='アニメ',
                    uri='my server addrsss'
                ),
                URITemplateAction(
                    label='音楽',
                    uri='my server addrsss'
                ),
                URITemplateAction(
                    label='映画',
                    uri='my server addrsss'
                ),
                URITemplateAction(
                    label='ドラマ',
                    uri='my server addrsss'
                )])
            )
        )
    # 당분간은 정규표현식 활용, 나중에 NLU로 발화 내 핵심 키워드 구분 처리
    
    elif re.search('날씨|일기예보',text) is not None:
        line_bot_api.reply_message(event.reply_token, TextSendMessage(text="お天気ですか"))
        location = 'location'
        subprocess.Popen(['python3', '/directory', '-l', location])
    
    elif re.search('11번가 검색|11번가|쇼핑|쇼핑 검색',text) is not None:
        keyword = re.search('[^11번가|11번가 검색|쇼핑|쇼핑 검색][a-zA-Z0-9가-힣]{1,100}', text).group(0)
        line_bot_api.reply_message(event.reply_token, TextSendMessage(text="ちょっと探してきますわよ"))
        subprocess.Popen(['python3', 'directory', '-k', keyword])

    # 일치하는 발화가 없는 경우
    else:
        line_bot_api.reply_message(
            event.reply_token, TextSendMessage(text=event.message.text))

if __name__ == "__main__":

    # SSL 인증서는 Let's Encrypt로 사용
    context = ('/directory/fullchain.pem', '/directroy/privkey.pem')

    # 0.0.0.0 = Can be access from anywhere. using port 5000, SSL
    app.run(host='0.0.0.0',port=5000, debug=True, ssl_context=context)

**Comment by doodspav** [comment]
the problem is that i had this error last time, and what was listening to the port was apache, and i couldnt find a way to stop it from listening. And if i use another port i still get this message:
myip - - [22/Nov/2017 04:03:01] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x03\x00\x97\x01\x00\x00\x93\x03\x03Z\x14\xf6\xf4&L\xa7\xa5]\x88\x83]\xc1\xc0*')
203.104.146.154 - - [22/Nov/2017 04:03:01] "▒▒Z▒▒&L▒▒]▒▒]▒▒* ▒I▒ƾ#▒▒y▒▒֟#▒.▒,▒+▒/▒▒▒/5Z" 400 -
which is why i was wondering if you could tell me how you set yours up.

**Comment by Sung-eon** [comment]
You can install OpenSSL for python by "pip install pyopenssl"

**Comment by Sung-eon** [comment]
Try to run your line.py with terminal 

For example, python3 (Directory of the file)

**Comment by doodspav** [comment]
for some reason your very long comment only just appeared - but it seems that the problem is that i didnt include the context bit in my app.run - will try that now and see what happens

**Comment by doodspav** [comment]
wow thank you so much :)!! im getting a 404 error now, but it's not complete gibberish, so id say its all but working now :) (btw for anyone reading this in the future, if for the context you cant find your .pem files just do `$ sudo find / -name '*.pem'`)
