### ISSUE TITLE
Really not sure where ive gone wrong...

### ISSUE THREAD

**Issue by doodspav** [line/line-bot-sdk-python#78]
create an ubuntu 16.04 server running a LAMP stack (from DigitalOcean)
link the domain name doodspav.com to the server

update and install pip
`$ sudo` apt-get update && sudo apt-get -y upgrade
$ sudo apt-get install python-pip
$ pip install --upgrade pip`

update and install SSL certificate
(from certbot.eff.org)
`$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install python-certbot-apache
$ sudo certbot --apache`

install line-bot-sdk and dependancies
`$ pip install future
$ pip install --upgrade requests
$ pip install line-bot-sdk
$ pip install --upgrade pyopenssl
$ pip install flask`

create line.py
(I've replaced the Channel Secret and Access Token)
Also i have no idea why i import OpenSSL

from flask import Flask, request, abort
from OpenSSL import SSL
from linebot import (
    LineBotApi, WebhookHandler
)
from linebot.exceptions import (
    InvalidSignatureError
)
from linebot.models import (
    MessageEvent, TextMessage, TextSendMessage,
)
app = Flask(__name__)
line_bot_api = LineBotApi('CHANNEL_ACCESS_TOKEN')
handler = WebhookHandler('CHANNEL_SECRET')
@app.route("/callback", methods=['POST'])
def callback():
    # get X-Line-Signature header value
    signature = request.headers['X-Line-Signature']`
    # get request body as text
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)
    # handle webhook body
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return 'OK'
@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text=event.message.text))
context = ("/etc/letsencrypt/live/doodspav.com/fullchain.pem","/etc/letsencrypt/live/doodspav.com/privkey.pem")
if __name__ == "__main__":
    app.run(host="0.0.0.0",port=5000,ssl_context=context)

i've put the webhook url as doodspav.com:5000/
then run the script

sudo ufw allow 5000
python line.py

this is the printed response on my server whenever i send a message in a chat with the bot:
`my_ip - - [24/Nov/2017 22:20:09] "POST / HTTP/1.1" 404 -`

i'm honestly not sure what to do since it looks like other peoples code

**Comment by Sung-eon** [comment]
Di you set your callback url in line console correctly?

In my case, I set callback url as https://(myserver).com:5000/callback

If you didn't write address properly, Be sure to include https, port number and /callback in line console.

**Comment by doodspav** [comment]
holy crap it works :)!!!!!! (i had just put https://(myserver)/com/5000) - idk how to thank you, you've helped so much
