### ISSUE TITLE
I got error message "LineBotApiError [Not found]"

### ISSUE THREAD

**Issue by derekdonyen** [line/line-bot-sdk-python#81]
I use the following simple code to test my line userid and push message.

```python
from linebot import LineBotApi
from linebot.models import TextSendMessage

line_bot_api = LineBotApi('mytoken')
#push message to one user
profile = line_bot_api.get_profile('my line user id')

print(profile.display_name)
print(profile.user_id)
print(profile.picture_url)
print(profile.status_message)

line_bot_api.push_message('my line user id', TextSendMessage(text='Hello World!'))
```

I am pretty sure this id is correct because  I use the other account in the same way can work.

However, this account will be an error message.(linebot.exceptions.LineBotApiError: <LineBotApiError [Not found]>) I also confirm that the settings are exactly the same.

Could you give me some advice?

Many thanks

**Comment by derekdonyen** [comment]
Supplementary explanation:
I found my line token can't query other person profile. It seems to be a token problem.
Did anyone encounter the same problem?

**Comment by uziins** [comment]
Are you sure your user id is correct? Is the bot created under same 'provider'?  Different provider give you different user id.

**Comment by derekdonyen** [comment]
Hello,

I am pretty sure the user id is correct because I use my colleague's token that could get profile and push message to everyone by user id.

As you said , I find different provider have different user id.

However I try to use different provider to get every token still not work.

Many thanks

從我的 iPhone 傳送

**Comment by derekdonyen** [comment]
I found the token can't push message to anyone and query profile. It seems token issues.
And I create a new account that still happen.

**Comment by clsung** [comment]
Please check if the token are all belong to the same provider. User IDs are unique for each provider that you create.

**Comment by derekdonyen** [comment]
Hello,

As you said, each provider has the unique User ID and token.

But every token still not work for me.

本通訊及其所有附件 (統稱 "本通訊" )
所含之資訊均屬機密，僅供指定之收件人使用。未經寄件人許可不得揭露、複製或散布本通訊。若您並非指定之收件人，請勿使用、保存或揭露本通訊之任何部份，並即通知寄件人且完全刪除本通訊。本通訊之陳述並不當然反映本公司及
/
或其關係企業之意見或看法。網路通訊無法保證安全、正確無誤或不含病毒，收件人應自行確認本郵件是否安全及未有被病毒入侵、被攔截的情況，若因此造成損害，寄件人恕不負責。為品質控管及法規遵循之目的，本公司及
/
或其關係企業得審視、保存並處理本郵件地址之往來電子郵件。本公司依個人資料保護法之要求蒐集、利用及處理您的個人資料。您與本郵件地址為通訊即代表您已同意上述所載事項。

The information contained in this communication and attachment (together,
the "this communication") is confidential and is for the use of the
intended recipient only. Any disclosure, copying or distribution of this
communication without the sender's consent is strictly prohibited. If you
are not the intended recipient, please notify the sender and delete this
communication entirely without using, retaining, or disclosing any of its
contents. Any statements contained in this communication do not necessarily
reflect those of our company and/or any of its affiliates. Internet
communications cannot be guaranteed to be secure, error-free or virus-free.
The recipient is responsible for ensuring that this communication is
secure, virus-free or not intercepted and the sender accepts no liability
for any damages caused therefrom. Our company and/or any of our company's
affiliates may review, retain and process the incoming and outgoing
electronic mail for this e-mail address for quality assurance and
regulatory compliance purposes. Our company collects, uses and processes
your personal information in accordance with the Personal Information
Protection Act. Your transmission of electronic mail to this address
represents your consent to the above-stated

Best Regards
Derek

2017-12-31 18:02 GMT+08:00 Cheng-Lung Sung <notifications@github.com>:

**Comment by be-hase** [comment]
If it is a token problem, you may get an error like the following.

```
LineBotApiError [Authentication failed due to the following reason: invalid token. Confirm that the access token in the authorization header is valid.]
```

So, it seems that userId is wrong.

**Comment by tokuhirom** [comment]
This issue will close once because there is no progress.
If you still have problems, please open a new issue.
