### ISSUE TITLE
Question about tagged group members

### ISSUE THREAD

**Issue by bottsjw** [line/line-bot-sdk-python#83]
Best I can tell, there is no way to enable the 'tagging' feature through the API such that by adding @username the group member is alerted as being 'mentioned in a post'... 
Is anyone aware of a way to do this through the API/this SDK?

Feel free to remove this question if it's totally off topic.
Thanks!

**Comment by doodspav** [comment]
As far as can tell there's no way to do this with the current api. Normally when you send a text message on line, you have the text (which is the characters in the message), and you also might have contentMetadata. When you tag someone, their mid is stored in the contentMetadata (along with some other stuff). With the current api , we are only given the text, and not the contentMetadata.

**Comment by bottsjw** [comment]
Got it. Yes, when I look at what's seen in messages manually sent via the app, I don't see anything unique about the tag. Just curious. Hopefully something they'll allow in the future.
Thanks @doodspav
