### ISSUE TITLE
Preview image is not updated

### ISSUE THREAD

**Issue by herleeyandi** [line/line-bot-sdk-python#86]
Hello I am trying to send an image data in my server to user. I have a static link to read the image. However we always update the image with different image with the same filename (overwrite). The original image file shows the right ones, but the preview always shows the first image (not updated version), but after I check in my server, both of the images have been updated. 
How to force line to read again the preview image even the link is same?

**Comment by clsung** [comment]
It may because the preview image is cached on the device. You can try to block/add the bot again to see if the preview image is correct.
