### ISSUE TITLE
Unexpect callback information on operation message. userId is null

### ISSUE THREAD

**Issue by adgj5472** [line/line-bot-sdk-python#89]
Because I use line-bot-sdk-python, so I file issue here.

I find the Line Server is not provide expect callback for operation.

When I try to get "event.message.userId" message on JSON, I get as follow:

    {
    "message": {     
                "id": "7221963375040",
                "text": "TEST", 
                "type": "text"
                }, 
                "replyToken": "33f330692e5b493d8ba400652d62c14b",
                "source": {
                            "groupId": "C6f9ddd71af67bb47a3b00950aa51b59c", 
                            "type": "group", 
                            "userId": null
                }, 
                "timestamp": 1514533485276,
                "type": "message"
    }

It missing some data under "userId" , so I cannot get "userId".

But it is not always happened.

Please let me know if you need any more detail.

Thank you.

**Comment by be-hase** [comment]
Probably, I think that the user does not provide consent.
so, userId is null.

ref:
https://developers.line.me/en/docs/messaging-api/user-consent/

**Comment by adgj5472** [comment]
Thank you.

This is the solution.
