### ISSUE TITLE
RichMenu is not display

### ISSUE THREAD

**Issue by eggeggss** [line/line-bot-sdk-python#97]
Hi
I created a rich menu, but I can't see anymore at line

> rich_menu_to_create = RichMenu(
                                 size=RichMenuBound(
                                  width=2500,
                                   height=1686
                                  ),
                            selected= False,
                            name="nice richmenu",
                            chatBarText="touch me",
                            areas=[
                                RichMenuArea(
                                    RichMenuBound(
                                        x=0,
                                        y=0,
                                        width=2500,
                                        height=1686
                                    ),
                                    URITemplateAction(
                                        uri='line://nv/location'
                                    )
                                )
                            ]
                        )
rich_menu_id = line_bot_api.create_rich_menu(data=rich_menu_to_create)

**Comment by quts** [comment]
Hi 

If there is an error occurred while creating a rich menu, would you please share with us what is that?
Additionally, after you create a rich menu, please continue to set_rich_menu_image and link_rich_menu_to_user. After that, you should able to see the rich menu on devices.

Thank you

**Comment by Diptags** [comment]
Hi @quts 
Seems files in this repository is not updated in pyPI website
https://pypi.org/project/line-bot-sdk/#history
So the latest version on the website is 1.5.0 (September 2017)
But the latest commit in this repo is March 1 2018

If I run "pip install line-bot-sdk" I cannot create a rich menu, because there's no API files in the sdk files....
Would you like to update the files on pyPI ? I cannot create rich menu and deploy it because there's no API for rich message in pyPI....

Thank you very much

**Comment by tokuhirom** [comment]
Currently, we uploaded the new version on PyPI. could you test it again?

**Comment by be-hase** [comment]
I will close it. Please reopen if there is still a problem.

**Comment by AwesomePeople** [comment]
Hi @quts, Hi everyone!
After I migrate my account ( in May, 2019). I have created menu in Line Official Account Manager page. I chosen the menu template and fill my menu fields. But after I chosen image background for menu. I see nothing, image background cover my menu content. Please help me! Thank you!
