### ISSUE TITLE
pip3 install line-bot-sdk error

### ISSUE THREAD

**Issue by JackHsuan** [line/line-bot-sdk-python#99]
#sudo pip3 install line-bot-sdk
Collecting line-bot-sdk
  Using cached line_bot_sdk-1.5.0-py2.py3-none-any.whl
Collecting future (from line-bot-sdk)
  Using cached future-0.16.0.tar.gz
    Complete output from command python setup.py egg_info:
    /opt/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'entry_points'
    /opt/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
    /opt/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
    /opt/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
    /opt/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: invalid command 'egg_info'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1djsaejn/future/

**Comment by tokuhirom** [comment]
There's an issue around your python installation.
